### ISSUE TITLE
Using kube-state-metrics for HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by vrathore18** [kubernetes/kube-state-metrics#1138]
I have kube-state-metrics in monitoring namespace, which I deployed using prometheus-operator in my EKS cluster.  I am implementing HorizontalPodAutoscaler in default namespace but couldn't found a documentation on how to use kube-state-metrics. 

Could you please guild me to the proper documentation or example if you have.

I can confirm that this is not working

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```

Can we have a proper sample hpa.yaml which uses kube-state-metrics??
