### ISSUE TITLE
Continuously getting Resources are not within the expected limits, updating the deployment

### ISSUE THREAD

**Issue by salimuddin87** [kubernetes/kube-state-metrics#1189]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
ERROR: logging before flag.Parse: I0729 12:29:42.255824       1 nanny_lib.go:108] Resources are not within the expected limits, updating the deployment. Actual: {Limits:map[memory:{i:{value:115343360 scale:0} d:{Dec:<nil>} s:110Mi Format:BinarySI} cpu:{i:{value:105 scale:-3} d:{Dec:<nil>} s:105m Format:DecimalSI}] Requests:map[cpu:{i:{value:105 scale:-3} d:{Dec:<nil>} s:105m Format:DecimalSI} memory:{i:{value:115343360 scale:0} d:{Dec:<nil>} s:110Mi Format:BinarySI}]} Expected: {Limits:map[cpu:{i:{value:110000000 scale:-9} d:{Dec:<nil>} s: Format:DecimalSI} memory:{i:{value:0 scale:0} d:{Dec:0xc42038d5f0} s: Format:BinarySI}] Requests:map[cpu:{i:{value:110000000 scale:-9} d:{Dec:<nil>} s: Format:DecimalSI} memory:{i:{value:0 scale:0} d:{Dec:0xc42038d5f0} s: Format:BinarySI}]}

**What you expected to happen**:
It should work properly

**How to reproduce it (as minimally and precisely as possible)**:
upgraded kube-state-metrics

**Anything else we need to know?**:
added in ClusterRole of kube-state-metrics
```
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Kube-state-metrics image version : 1.9.7
- addon-resizer image version: 1.8.3

**Comment by brancz** [comment]
That looks like it is a problem with the addon resizer pod, not kube-state-metrics.

**Comment by salimuddin87** [comment]
Here is addon-resizer deployment script.
```
- name: addon-resizer
        image: 530710445070.dkr.ecr.us-east-1.amazonaws.com/misearch-ecr-dev:addon-resizer-1.8.3
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container=kube-state-metrics
          - --cpu=100m
          - --extra-cpu=1m
          - --memory=200Mi
          - --extra-memory=2Mi
          - --threshold=5
          - --deployment=kube-state-metrics

```
