### ISSUE TITLE
Mismatch between readme and actual container

### ISSUE THREAD

**Issue by wacuuu** [kubernetes/kube-state-metrics#1194]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a bug
> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

readme says that --resources are used to point on what to monitor, but the error message when you actually try to use this switch says you should use --collectors, which work. I'm using container from quay in 1.9.7 version

**What happened**:
Container did not start with example params provided in readme
**What you expected to happen**:
fix readme or code
**How to reproduce it (as minimally and precisely as possible)**:
```
- name: kube-state-metrics
        image: quay.io/coreos/kube-state-metrics:v1.9.7
        imagePullPolicy: IfNotPresent
        args:
          - '--resources=pods'
```
the above will fail with info that resources is not recognized key
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Kube-state-metrics image version 1.9.7
