### ISSUE TITLE
some pod does not exists in kube_pod_container_resource_limits_memory_bytes  metric

### ISSUE THREAD

**Issue by hansedong** [kubernetes/kube-state-metrics#1243]
/kind bug

**What happened**:

The kube-state-metrics server export pod metrics, and I created a pod named  `327390-admin-mbrand-78bf674f4b-bdth6` in my K8s cluster by Deployment. 
I can see the pod with `kubectl get po` command
```
[root@node1 ssy]# kubectl get po 327390-admin-mbrand-78bf674f4b-bdth6 -n mbrand -o wide
NAME                                   READY   STATUS    RESTARTS   AGE   IP              NODE              NOMINATED NODE   READINESS GATES
327390-admin-mbrand-78bf674f4b-bdth6   1/1     Running   0          32h   10.131.x.x   node10-131-x-x   <none>           <none>
```
But the pod does not exists in metrics with the `kube_pod_container_resource_limits_memory_bytes` type ( it exists in other metrics types, e.g `kube_pod_container_status_restarts_total{container="application",namespace="mbrand",pod="327390-admin-mbrand-78bf674f4b-bdth6"} 0` ). 

**What you expected to happen**:

There should be a record in metrics just like `kube_pod_container_resource_limits_memory_bytes{container="...",namespace="...",node="...",pod="327390-admin-mbrand-78bf674f4b-bdth6"} 1.073741824e+09`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

My depoyments

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    appid: "1094"
    appname: admin
    branch: master
    deployment.kubernetes.io/revision: "1"
    desc: 本次发布版本tag==> 修改bug
    ms-deploy-operator: 1715-wangjiapeng
    sidecar.istio.io/concurrency: "2"
    sidecar.istio.io/inject: "true"
    traffic.sidecar.istio.io/includeOutboundIPRanges: 5.6.7.8/32
    vname: v0.0.1101
  name: 327390-admin-mbrand
  namespace: mbrand
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: admin.mbrand
      cadvisor-app: admin-mbrand
      microservice: rudder
      version: "327390"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        appid: "1094"
        appname: admin
        branch: master
        desc: 本次发布版本tag==> 修改bug
        sidecar.istio.io/concurrency: "2"
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/includeOutboundIPRanges: 5.6.7.8/32
        vname: v0.0.1101
      creationTimestamp: null
      labels:
        app: admin.mbrand
        cadvisor-app: admin-mbrand
        microservice: rudder
        version: "327390"
    spec:
      containers:
      - env:
        - name: MAFENGWO_MSERVICE
          value: "true"
        - name: PHYSICAL_DOCKER0_IP
          value: 172.17.0.1
        - name: PHYSICAL_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: APP_VERSION
          value: 0.0.1101
        image: hub.xxx.com/mbrand/admin:v0.0.1101
        imagePullPolicy: Always
        name: application
        ports:
        - containerPort: 80
          name: http-80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Accept
              value: '*/*'
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /xxx_rundata/logdata/machine
          name: svc-log
        - mountPath: /xxx_rundata/log
          name: java-platform-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub-xxxdev-com
      nodeSelector:
        msbiz: "on"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /xxx_rundata/logdata/k8s/kraken/mbrand/admin/v0.0.1101
          type: DirectoryOrCreate
        name: svc-log
      - hostPath:
          path: /xxx_rundata/logdata/java-platform/kraken/mbrand/admin/v0.0.1101
          type: DirectoryOrCreate
        name: java-platform-log
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Kube-state-metrics image version
kube-state-metrics:v1.4.0
