### ISSUE TITLE
There is a problem with the document

### ISSUE THREAD

**Issue by Wang-Kai** [kubernetes/kube-state-metrics#1267]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The [usage part](https://github.com/kubernetes/kube-state-metrics#usage) of `README.md` document dose not match the actual kube-state-metrics program . The paramter `--namespace` is not workable .

```yaml
spec:
  template:
    spec:
      containers:
      - name: kube-state-metrics
        args:
          - '--resources=pods'
          - '--namespace=project1'
```

**What you expected to happen**:

As written in the [code](https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/options/options.go#L88), there should be `--namespaces` rather than `--namespace`.

**How to reproduce it (as minimally and precisely as possible)**:

Modify the `README.md` file.

**Anything else we need to know?**:

Nothing
