### ISSUE TITLE
Can't get metrics `kube_pod_deletion_timestamp` when call delete pod

### ISSUE THREAD

**Issue by vinhha96** [kubernetes/kube-state-metrics#1281]
/kind bug

**What happened**:
When I call to delete a pod, but I can't get metrics `kube_pod_deletion_timestamp` from `kube-state-metrics`. although when I run the command `kubectl get pod / ... -oyaml` it already has the parameter deletion_timestamp.
I am not sure if there is any version incompatibility here?

> This is info of pod when run `kubectl get pod/vinhha-krjhn -oyaml`
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2020-10-27T03:13:03Z"
  deletionGracePeriodSeconds: 60
  deletionTimestamp: "2020-10-27T03:14:38Z"
  generateName: vinhha-
  labels:
    hpc-compute: ba57a6a3-9f9f-4965-ac83-7e820db94ef0
  name: vinhha-krjhn
  ...
```

> This is info of pod when run `kubectl describe pod/vinhha-krjhn`. Now pod's state is `Terminating`
```
kubectl describe pod/vinhha-krjhn
Name:                      vinhha-krjhn
Namespace:                 default
Priority:                  0
Node:                      ip-10-1-2-211.ap-southeast-1.compute.internal/10.1.2.211
Start Time:                Tue, 27 Oct 2020 10:13:03 +0700
Labels:                    hpc-compute=ba57a6a3-9f9f-4965-ac83-7e820db94ef0
Annotations:               kubernetes.io/psp: eks.privileged
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  60s
```

**What you expected to happen**:
I expect that when the pod is in Terminate state and the pod has recorded the time being called deleted, the `kube-state-metrics` can also get the pod's` kube_pod_deletion_timestamp` information.

**How to reproduce it (as minimally and precisely as possible)**:
- Step 1: Create new pod, and pod's state is Running
- Step 2: Call to delete Pod (ex via `kubectl`, ...) and pod's state change from `Running` to `Terminate`
- Step 3: While the pod is in Terminate, you can check in two places for the pod's information:
     + Get pod metrics from `kube-state-metrics`
     + Describe and get pod information via `kubectl`

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.17**
- Kube-state-metrics image version **v1.9.7**
