### ISSUE TITLE
Support for ingress status hostname

### ISSUE THREAD

**Issue by ofen** [kubernetes/kube-state-metrics#1366]
It would be great to have ability to collect metrics of ingress status from **status.loadBalancer.ingress[]** for ALB loadbalancer hostnames:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internal
    kubernetes.io/ingress.class: public-alb
  generation: 1
  name: test
  namespace: kube-system
spec:
  backend:
    serviceName: my-service
    servicePort: 8080
status:
  loadBalancer:
    ingress:
    - hostname: internal-9a4003c3-kube-system-test-bbc4-1234567890.us-east-1.elb.amazonaws.com
```
