### ISSUE TITLE
Allow for namespace flag to be passed as a list

### ISSUE THREAD

**Issue by costimuraru** [kubernetes/kube-state-metrics#1374]
**What would you like to be added**:
Currently, the namespace flag can be passed as a comma separated string.
`namespace: 'ns1,ns2,ns3'`
To make things consistent with the other charts, it would be helpful to be able to also pass it as a list:
```yaml
namespace: 
  - ns1
  - ns2,
  - ns3
```
Prometheus chart accepts a list:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1281

**Why is this needed**:
Because of the inconsistency between kube-state-metrics and kube-prometheus-stack, we have to duplicate the namespace list in our helm values file:

```yaml
  monitored_namespaces: &monitored_namespaces
    - ns-team1
    - ns-team2
    - ns-team3
    - ns-team4
    - ns-team5

  kube-state-metrics:
    namespace: ns-team1,ns-team2,ns-team3,ns-team4,ns-team5

  prometheusOperator:
    namespaces:
      additional: *monitored_namespaces

**Describe the solution you'd like**

Allow for namespace flag to also be passed as a list. 

```yaml
  kube-state-metrics:
    namespace: *monitored_namespaces

  prometheusOperator:
    namespaces:
      additional: *monitored_namespaces
```

**Additional context**
