### ISSUE TITLE
Add a new metric for HorizontalPodAutoscalar metrics with scaleTargetRef values

### ISSUE THREAD

**Issue by mpritter76** [kubernetes/kube-state-metrics#1395]
**What would you like to be added**:
A new metric that would provide reference details for HPA's. 

**Why is this needed**:
Like the kube_horizontalpodautoscaler_labels metric that simply provides label details for the HPA, this new metric would provide data about the HPA spec.scaleTargetRef 

**Describe the solution you'd like**
Example HPA YAML:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    annotation1: annotation1_value
  labels:
    label1: label1_value
  name: hpa1
  namespace: ns1
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: target_deployment_name
  targetCPUUtilizationPercentage: 90
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1
```

Possible NEW Metric: 
```
kube_horizontalpodautoscaler_spec_scale_target_ref{horizontalpodautoscaler="hpa1",namespace="ns1",apiVersion="apps/v1",kind="Deployment",name="target_deployment_name"} 1
```
