### ISSUE TITLE
kube-state-metrics does not some metrics

### ISSUE THREAD

**Issue by bmy4415** [kubernetes/kube-state-metrics#1414]
**What happened**:
According to my understanding, kube-state-metrics should collect metrics through all namespaces. But after querying to prometheus, I found that some metrics are skipped.

The docs says that default value of `namespaces` argument is "" which means all namespaces.

**What you expected to happen**:
kube-state-metrics exposes all metrics from all namespaces.

**How to reproduce it (as minimally and precisely as possible)**:
I think sharing the manifest files I used is best to explain my situation.
```yaml
# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.8.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kube-state-metrics
```

PromQL query I used
```
kube_pod_container_resource_limits_cpu_cores
```

PromQL query result 
```
# Only 1 result though many other pods are running.
kube_pod_container_resource_limits_cpu_cores{container="controller", instance="kube-state-metrics.kube-system.svc.cluster.local:8080", job="kube-state-metrics", namespace="kube-system", node="ip-192-168-88-94.ap-northeast-2.compute.internal", pod="aws-load-balancer-controller-6fc4b6f594-h2wmx"}
```

Below are pods running in my cluster.
```
❯ k get po --all-namespaces
NAMESPACE      NAME                                             READY   STATUS    RESTARTS   AGE
cert-manager   cert-manager-649c5f88bc-w6j9p                    1/1     Running   0          19d
cert-manager   cert-manager-cainjector-9747d56-8zdsv            1/1     Running   0          19d
cert-manager   cert-manager-webhook-849c7b574f-9dcpw            1/1     Running   0          19d
default        bering-redis-566d79569b-g5pxw                    1/1     Running   0          27d
default        bering-server-f57f44795-n2rvz                    1/1     Running   0          7d23h
default        bering-server-f57f44795-n9zqw                    1/1     Running   0          7d23h
default        bering-server-fluent-bit-6885f85bd9-z5fnb        1/1     Running   0          20d
default        bering-server-nginx-77c5747bb4-7cghd             1/1     Running   0          25d
default        onmt-server-b7958b4cf-dtfwq                      1/1     Running   0          20d
default        onmt-server-fluent-bit-664cd75d6-h8p2p           1/1     Running   0          20d
default        translation-server-6f74f696cf-f26b7              1/1     Running   0          8d
default        translation-server-fluent-bit-6967fd45f7-qhr4j   1/1     Running   0          20d
kube-system    aws-load-balancer-controller-6fc4b6f594-h2wmx    1/1     Running   0          19d
kube-system    aws-node-cbgrx                                   1/1     Running   0          30d
kube-system    aws-node-r26ws                                   1/1     Running   0          30d
kube-system    aws-node-sbd8v                                   1/1     Running   0          20d
kube-system    aws-node-smpns                                   1/1     Running   0          30d
kube-system    aws-node-v4kv9                                   1/1     Running   0          20d
kube-system    coredns-6fb4cf484b-htshr                         1/1     Running   0          30d
kube-system    coredns-6fb4cf484b-kxktf                         1/1     Running   0          30d
kube-system    kube-proxy-77j7d                                 1/1     Running   0          30d
kube-system    kube-proxy-7gcwb                                 1/1     Running   0          20d
kube-system    kube-proxy-h7ww4                                 1/1     Running   0          30d
kube-system    kube-proxy-jgpvz                                 1/1     Running   0          20d
kube-system    kube-proxy-snz6b                                 1/1     Running   0          30d
kube-system    kube-state-metrics-6dc8f4d86d-zm4mt              1/1     Running   0          5d22h
monitoring     grafana-64cd46cb84-lmsc7                         1/1     Running   0          5d22h
monitoring     node-exporter-dj4jj                              1/1     Running   0          28h
monitoring     node-exporter-frvw8                              1/1     Running   0          28h
monitoring     node-exporter-mkcdm                              1/1     Running   0          28h
monitoring     node-exporter-n8s8b                              1/1     Running   0          28h
monitoring     node-exporter-wflf9                              1/1     Running   0          28h
monitoring     prometheus-deployment-56f7986969-nxgxf           1/1     Running   0          5h24m
```

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: `v1.8.0`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: aws eks
- Other info:

**Comment by lilic** [comment]
@bmy4415 hello 👋  I would suggest to really upgrade the version of kube-state-metrics to either the latest release candidate or at least v1.9.x.

With that said can you share the ClusterRole and ClusterRoleBinding for this deployment? Thanks!

**Comment by bmy4415** [comment]
@lilic hi, I upgraded kube-state-metrics image to `quay.io/coreos/kube-state-metrics:v2.0.0-rc.0` which seems to be latest.
According to [release note](https://github.com/kubernetes/kube-state-metrics/blob/8e35f790041384c12f36b40c47bae05e15c6f243/CHANGELOG.md),`kube_pod_container_resource_limits_cpu_cores` is changed to `kube_pod_container_resource_limits_cpu_cores`.

But still, my PromQL `kube_pod_container_resource_limits` only shows metrics from pods in `kube-system` namespace, i.e, `aws-load-balancer-controller-6fc4b6f594-h2wmx `, `coredns-6fb4cf484b-htshr `, `coredns-6fb4cf484b-kxktf`. I'm not sure why metrics from other pods are not collected.

Below is ClusteRole and ClusterRoleBinding.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups:
  - ""
  resources: ["configmaps", "secrets", "nodes", "pods", "services", "resourcequotas", "replicationcontrollers", "limitranges", "persistentvolumeclaims", "persistentvolumes", "namespaces", "endpoints"]
  verbs: ["list","watch"]
- apiGroups:
  - extensions
  resources: ["daemonsets", "deployments", "replicasets", "ingresses"]
  verbs: ["list", "watch"]
- apiGroups:
  - apps
  resources: ["statefulsets", "daemonsets", "deployments", "replicasets"]
  verbs: ["list", "watch"]
- apiGroups:
  - batch
  resources: ["cronjobs", "jobs"]
  verbs: ["list", "watch"]
- apiGroups:
  - autoscaling
  resources: ["horizontalpodautoscalers"]
  verbs: ["list", "watch"]
- apiGroups:
  - authentication.k8s.io
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups:
  - authorization.k8s.io
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups:
  - policy
  resources: ["poddisruptionbudgets"]
  verbs: ["list", "watch"]
- apiGroups:
  - certificates.k8s.io
  resources: ["certificatesigningrequests"]
  verbs: ["list", "watch"]
- apiGroups:
  - storage.k8s.io
  resources: ["storageclasses", "volumeattachments"]
  verbs: ["list", "watch"]
- apiGroups:
  - admissionregistration.k8s.io
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources: ["networkpolicies"]
  verbs: ["list", "watch"]
```

THanks!
