### ISSUE TITLE
VerticalPodAutoScaler metrics are not shown

### ISSUE THREAD

**Issue by ThaSami** [kubernetes/kube-state-metrics#1439]
**What happened**:
Deployed kube-state-metrics over k8s 1.19 with Latest VPA ( master ) and used v1beta2 API and i couldn't see the VPA metrics
 
**What you expected to happen**:
The VPA metrics to be shown in kube-state-metrics such as target, upper_bound, lower_bound etc..

**Environment**:
- kube-state-metrics version: from the release 2.0.0 

- Kubernetes version (use `kubectl version`):

> -Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8+rke2r1", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-26T00:03:32Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8+rke2r1", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-26T00:03:32Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by lilic** [comment]
@ThaSami thanks for the bug report! I assume you followed the docs to configure VPA https://github.com/kubernetes/kube-state-metrics/blob/master/docs/verticalpodautoscaler-metrics.md#Configuration?

Do you mind sharing your deployment as well as the VPA objects so we can try to reproduce, thank you!

**Comment by ThaSami** [comment]
Hi @lilic, Thanks for replying.
Yes, i've followed the documentation you've mentioned, at first, I've deployed the latest (master) version of VPA then did a clean-up and installed the latest release 0.9 with v1beta2 CRDS. 

below you can find my deployment of kube-state-metric, and the VPA object.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-rc.1
  name: kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/version: 2.0.0-rc.1
    spec:
      containers:
      - image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.1
        args:
          - --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers, ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,verticalpodautoscalers,volumeattachments
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
        securityContext:
          runAsUser: 65534
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kube-state-metrics
```

VPA 

```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       cpu-stress
  updatePolicy:
    updateMode: "Off"
```
I've installed the VPA by running the "vpa-up" script then applied v1beta2 CRD. 


```
# curl -s 10.42.0.189:8081/metrics | grep -i verticalpodautoscaler
kube_state_metrics_list_total{resource="*v1beta2.VerticalPodAutoscaler",result="error"} 444
```

**Comment by lilic** [comment]
Thanks, did you adjust your permissions as well in the [cluster role](https://github.com/kubernetes/kube-state-metrics/blob/master/examples/standard/cluster-role.yaml)?

**Comment by ThaSami** [comment]
Thanks lilic 
i believe I've done so, please check 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-rc.1
  name: kube-state-metrics
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - verticalpodautoscalers
  - verticalpodautoscalercheckpoints
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
```

**Comment by lilic** [comment]
Thanks, can you also share the logs of kube-state-metrics, thank you!

**Comment by ThaSami** [comment]
@lilic thanks for pointing out, the issue was due to permissions. I see that VPA is under autoscaling.k8s.io not autoscaling API
adding this to cluster-role fixed the issue
```
- apiGroups:
  - autoscaling
  resources:
  - verticalpodautoscalers
  - verticalpodautoscalercheckpoints
  verbs:
  - list
  - watch
```
