### ISSUE TITLE
kube_namespace_labels broken in 2.0.0

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kube-state-metrics#1477]
**What happened**: We upgraded from 1.9.8 to 2.0.0 kube-state-metrics

After that we can see data like
```
kube_namespace_labels{container="kube-rbac-proxy-main", instance="100.114.162.71:8443", job="kube-state-metrics", namespace="kube-system"}
```

With version 1.9.8 the data is

```
kube_namespace_labels{container="kube-rbac-proxy-main", instance="100.116.33.233:8443", job="kube-state-metrics", label_addon_kops_k8s_io_name="core.addons.k8s.io", label_addon_kops_k8s_io_version="1.4.0", label_app_kubernetes_io_managed_by="kops", label_kubernetes_io_metadata_name="kube-system", label_maintainer="sre", namespace="kube-system"}
```

**What you expected to happen**: I expect that kube_namespace_labels metric should show the metrics that it should.

**How to reproduce it (as minimally and precisely as possible)**: Start 2.0.0 kube-state-metrics and query for kube_namespace_labels (first check that you have some labels in namespaces)

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version:  2.0.0
- Kubernetes version (use `kubectl version`): -
- Cloud provider or hardware configuration: openstack/aws
- Other info:

**Comment by lilic** [comment]
Hey 👋 this is not a bug, but a feature :) We mentioned this in the blog and changelog under the labels section https://kubernetes.io/blog/2021/04/13/kube-state-metrics-v-2-0/#what-is-new-in-v2-0

> Flag --metric-labels-allowlist allows you to specify a list of Kubernetes labels that get turned into the dimensions of the kube_<resource-name>_labels metrics. By default, the metric contains only name and namespace labels.

For further help have a look at the --help how to use this. Let me know if you have any other questions or if we should document this elsewhere.

**Comment by zetaab** [comment]
I cannot get it working with 2.0.0 with that `--metric-label-allowlist` either.

from deployment:
```
      containers:
      - args:
        - --host=127.0.0.1
        - --port=8081
        - --telemetry-host=127.0.0.1
        - --telemetry-port=8082
        - --metric-labels-allowlist=label_maintainer,maintainer
        image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0
```
