### ISSUE TITLE
kube_pod_container_status_restarts_total not reporting restarts accurately

### ISSUE THREAD

**Issue by OscarLuu** [kubernetes/kube-state-metrics#1568]
**What happened**:
We looked into the Metrics Explorer to create a new alert on container restarts, we noticed that the number of restarts when checking the cluster with `kubectl get po` would show that a pod restarted a few times. When we used the GCP metric explorer to confirm that the values were accurate we saw that the metric explorer had 0 occurrences of restarts per pod. 

![image](https://user-images.githubusercontent.com/26631484/131742453-8ab3fb75-7975-46df-80ba-1936609a6ad6.png)
![image](https://user-images.githubusercontent.com/26631484/131742732-d7d38f4b-bfb4-4bae-bc61-e3a42879959b.png)

```
fetch gke_container
| metric 'custom.googleapis.com/kube-state/<cluster>/kube_pod_container_status_restarts_total'
| filter metric.pod == "oomtester-7c766c779c-zx4f4"
```
**What you expected to happen**:
We expected the GCP Metrics Explorer to report the same number of restarts to what we see when we do `kubectl get pods`. 

**How to reproduce it (as minimally and precisely as possible)**:
We first noticed it in pods running workloads, so we replicated it by creating a new deployment in a new namespace.
* `kubectl create namespace <test ns>`
* created a new deployment in this namespace
```
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "oomtester"
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: "oomtester"
  template:
    metadata:
      labels:
        app: "oomtester"
    spec:
      containers:
      - name: "oomtester"
        image: "ubuntu:latest"
        resources:
          limits:
            memory: 5Mi 
```
* wait for the pod to spin a new container up, it should crashloop and cause some restarts to be noted. 
* verify that pod restarts have occurred by getting the pod.
* Check the metrics explorer and run another query to see if the restart values have been updated.

**Environment**:
- kube-state-metrics version: 2.2.0
- Kubernetes version (use `kubectl version`): 1.22.0
- Cloud provider or hardware configuration: GCP 
- Other info:
