### ISSUE TITLE
HPA using a custom metric of type Object is not visible in `kube_horizontalpodautoscaler_spec_target_metric`

### ISSUE THREAD

**Issue by flaker** [kubernetes/kube-state-metrics#1594]
**What happened**:

I have a custom metric (via Prometheus Adapter) to drive the HPA of a certain deployment. It's an Object metric, in this case a Deployment. The target type is "Value"

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myHPA
spec:
  minReplicas: 10
  maxReplicas: 100
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myDeployment
  metrics:
  - type: Object
    object:
      metric:
        name: my_custom_metric_from_prometheus_adapter
      describedObject:
        kind: Deployment
        apiVersion: apps/v1
        name: myDeployment
      target:
        type: Value
        value: 0.5

```
The HPA is behaving as expected scaling the deployment. BUT when I query `kube_horizontalpodautoscaler_spec_target_metric` my HPA is not there. Other HPA based on custom metrics but applied to Pods (a more common case?) are visible.

**What you expected to happen**:

My HPA should be there along with others. To note, in other metrics (e.g. kube_horizontalpodautoscaler_spec_min_replicas) I do see the name of my HPA.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.0.0
- Kubernetes version (use `kubectl version`): v1.16.9
- Cloud provider or hardware configuration: ad-hoc k8s cluster
- Other info:
