### ISSUE TITLE
metric_relabel_configs does not work as expected

### ISSUE THREAD

**Issue by yongzhang** [kubernetes/kube-state-metrics#1628]
**What happened**:

I have kube-state-metrics starts with arg:
```
        - --metric-labels-allowlist=deployments=[app.kubernetes.io/name,app,k8s-app,owner],daemonsets=[app.kubernetes.io/name,app,k8s-app,owner],pods=[app.kubernetes.io/name,app,k8s-app,owner],cronjobs=[app.kubernetes.io/name,app,k8s-app,owner],jobs=[app.kubernetes.io/name,app,k8s-app,owner]
```

And defined scrap like this in prometheus, what I want is to replace label name  `k8s-app` or `app` to `app.kubernetes.io/name`
```
        - job_name: 'kube_state_metrics'
          scheme: https
          static_configs:
            - targets: ['kube-state-metrics.mydomain']
          relabel_configs:
            - source_labels: ['__metrics_path__']
              target_label: metrics_path
            - source_labels: ['__scheme__']
              target_label: metrics_scheme
          metric_relabel_configs:
            - source_labels: [label_k8s_app]
              target_label: label_app_kubernetes_io_name
            - source_labels: [label_app]
              target_label: label_app_kubernetes_io_name
```
But it doesn't work, I got:
![image](https://user-images.githubusercontent.com/15604715/140922165-c398333d-0bd4-4995-b227-debdcaa38357.png)

Not sure if I defined wrong `metric_relabel_configs` or any other issues, please help, thanks.

**Environment**:
- kube-state-metrics version:  v2.2.0
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration: AWS EKS
- Other info:
