### ISSUE TITLE
kube-state-metrics pod error: Failed to create client: error while trying to communicate with apiserver: Get "https://172.20.0.1:443/version?timeout=32s": Forbidden

### ISSUE THREAD

**Issue by PriyaTenneti** [kubernetes/kube-state-metrics#1630]
**What happened**:
When using custom-built kube-state-metrics image, kube-state-metrics is in CrashLoopBackOffState and getting following forbidden error.
```
$ kubectl logs -f prometheus-kube-state-metrics-84648f9f4-b7qz5
I1113 21:04:25.495462      14 main.go:98] Using resources certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachmentsI1113 21:04:25.495538      
14 main.go:107] Using all namespaceI1113 21:04:25.495578      
14 main.go:128] metric allow-denylisting: Excluding the following lists that were on denylist:W1113 21:04:25.495621      
14 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.This might not work.I1113 21:04:25.496890      
14 main.go:234] Testing communication with serverF1113 21:04:25.512245      
14 main.go:138] Failed to create client: error while trying to communicate with apiserver: Get "https://172.20.0.1:443/version?timeout=32s": Forbidden
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00012a001, 0xc00040c000, 0xb2, 0xcf)
        /go/src/k8s.io/kube-state-metrics/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x21f4da0, 0xc000000003, 0x0, 0x0, 0xc0003c7730, 0x2153276, 0x7, 0x8a, 0x0)
        /go/src/k8s.io/kube-state-metrics/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x21f4da0, 0x3, 0x0, 0x0, 0x1703302, 0x1b, 0xc0001b5ce0, 0x1, 0x1)        /go/src/k8s.io/kube-state-metrics/vendor/k8s.io/klog/v2/klog.go:733 +0x17ak8s.io/klog/v2.Fatalf(...)        /go/src/k8s.io/kube-state-metrics/vendor/k8s.io/klog/v2/klog.go:1456main.main()        /go/src/k8s.io/kube-state-metrics/main.go:138 +0xa85goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x21f4da0)
        /go/src/k8s.io/kube-state-metrics/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /go/src/k8s.io/kube-state-metrics/vendor/k8s.io/klog/v2/klog.go:416 +0xd8
```
**What you expected to happen**:
kube-state-metrics pod to be in running state.

**How to reproduce it (as minimally and precisely as possible)**:
I am using following Dockerfile to create the kube-state-metrics in EKS cluster
```
ARG GOVERSION=1.15
FROM golang:${GOVERSION} as builder
ARG GOARCH=amd64
ENV GOARCH=${GOARCH}
WORKDIR /go/src/k8s.io/kube-state-metrics/
COPY . /go/src/k8s.io/kube-state-metrics/

RUN make build-local
RUN apt-get update -y && apt-get install -y vim
FROM golang:${GOVERSION}
COPY --from=builder /go/src/k8s.io/kube-state-metrics/kube-state-metrics /

WORKDIR /
ENV DEFENDER_TYPE="appEmbedded"
ENV DEFENDER_APP_ID="foo-prometheus-kube-state-metrics-np"
ENV WS_ADDRESS="wss://foo-bar.cloud.twistlock.com:443"
ENV DATA_FOLDER="/home"
ENV INSTALL_BUNDLE="<random-string-from-vendor>

ADD twistlock_defender_app_embedded.tar.gz /home

ENTRYPOINT [ "/home/defender", "--LOG_PROD", "app-embedded", "/kube-state-metrics", "--port=8080", "--telemetry-port=8081", "--resources=certificatesigningrequests", "--resources=configmaps", "--resources=cronjobs", "--resources=daemonsets", "--resources=deployments", "--resources=endpoints", "--resources=horizontalpodautoscalers", "--resources=ingresses", "--resources=jobs", "--resources=limitranges", "--resources=mutatingwebhookconfigurations", "--resources=namespaces", "--resources=networkpolicies", "--resources=nodes", "--resources=persistentvolumeclaims", "--resources=persistentvolumes", "--resources=poddisruptionbudgets", "--resources=pods", "--resources=replicasets", "--resources=replicationcontrollers", "--resources=resourcequotas", "--resources=secrets", "--resources=services", "--resources=statefulsets", "--resources=storageclasses", "--resources=validatingwebhookconfigurations", "--resources=volumeattachments"]

EXPOSE 8080 8081
```
This is the kubernetes deployment of kube-state-metrics
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0
    helm.sh/chart: kube-state-metrics-3.1.1
  name: prometheus-kube-state-metrics
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/name: kube-state-metrics
    spec:
      containers:
      - image: 545258875.dkr.ecr.us-east-1.amazonaws.com/quay.io/coreos/kube-state-metrics:vappdef-nplatest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 15
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-kube-state-metrics
      serviceAccountName: prometheus-kube-state-metrics
      terminationGracePeriodSeconds: 30
```

**Environment**:
- kube-state-metrics version: v2.0.0-beta
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: no
