### ISSUE TITLE
Add Metrics for Job ownerReferences

### ISSUE THREAD

**Issue by ulikl** [kubernetes/kube-state-metrics#1639]
**What would you like to be added:**
A new metric which provides owner reference details for Jobs.

**Why is this needed:**
I would like to aggregate the jobs by it owners similar to created_by_kind/created_by_name for pod via kube_pod_info.

**Describe the solution you'd like**
Example Job YAML:

 ```
apiVersion: batch/v1
  kind: Job
  metadata:
    creationTimestamp: "2021-11-18T08:00:05Z"
    labels:
      job-name: my-trigger-1637222400
      parent: my-trigger
    name: my-trigger-1637222400
    namespace: my-namespace
    ownerReferences:
    - apiVersion: batch/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: my-trigger
      uid: 245e548a-9f24-11ea-ac78-fa163e1d3f3e
  ...
```

Possible NEW Metric:

`kube_job_owner_reference{namespace="my-namespace",job_name="my-trigger-1637222400",owner_kind="CronJob",owner_name="my-trigger"} 1`
