### ISSUE TITLE
Custom Resource configuration may lead to invalid metricname

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/kube-state-metrics#1753]
**What happened**:

Started kube-state-metrics using the following args:
```
go run ./ --kubeconfig $KUBECONFIG --custom-resource-state-config-file custom.yaml
```

And the following `custom.yaml`:
```yaml
kind: CustomResourceStateMetrics
spec: 
  resources: 
    - groupVersionKind: 
        group: cluster.x-k8s.io
        kind: MachineDeployment
        version: v1beta1
      metrics: 
        - name: spec_replicas
          each: 
            path: 
              - spec
              - replicas
```

The corresponding created metric has the following name `kube_cluster_x-k8s_io_v1beta1_MachineDeployment_spec_replicas`.

```
I0608 21:52:49.269160    4564 registry_factory.go:442] custom resource state adding metrics: [kube_cluster_x-k8s_io_v1beta1_MachineDeployment_spec_replicas]
```

This metric name is invalid due to the `-` character according:

* the [openmetrics ABNF](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#abnf)
  ```
  metricname = metricname-initial-char 0*metricname-char
  metricname-char = metricname-initial-char / DIGIT
  metricname-initial-char = ALPHA / "_" / ":"
  ```
* the metric name definition at [the prometheus docs](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)
  
  > The metric name specifies the general feature of a system that is measured (e.g. http_requests_total - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. 
  > **It must match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`.**
  
  
**What you expected to happen**:

A metric for a custom resource gets created having metric name `kube_cluster_x_k8s_io_v1beta1_MachineDeployment_spec_replicas`.

**How to reproduce it (as minimally and precisely as possible)**:

Create `custom.yaml`:
```
kind: CustomResourceStateMetrics
spec: 
  resources: 
    - groupVersionKind: 
        group: cluster.x-k8s.io
        kind: MachineDeployment
        version: v1beta1
      metrics: 
        - name: spec_replicas
          each: 
            path: 
              - spec
              - replicas
```

And run kube-state-metrics:

```
go run ./ --kubeconfig $KUBECONFIG --custom-resource-state-config-file custom.yaml
```

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.5.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info: after running [quick-start-guide for cluster-api](https://cluster-api.sigs.k8s.io/user/quick-start.html)
