### ISSUE TITLE
Cannot read the timestamp field from Custom Resource metadata with the new customresource metrics capability

### ISSUE THREAD

**Issue by dontan001** [kubernetes/kube-state-metrics#1765]
**What would you like to be added**:
It could be either a bug or feature request, assume it is a feature request for now

We would like to expose the creationTimestamp of Custom Resource with the capability from #1710 , then we could visualize it via Grafana annoation.

During the testing, the major config looks like below
```
          - --custom-resource-state-config
          -  |
              spec:
                resources:
                  - groupVersionKind:
                      group: scheduling.volcano.sh
                      version: "v1beta1"
                      kind: PodGroup
                    labelsFromPath:
                      name: [metadata, name]
                      namespace: [metadata, namespace]
                    metrics:
                    - name: creation_timestamp
                      help: "Creation time of PodGroup"
                      each:
                        path: [metadata, creationTimestamp]
```

However we cannot find any metrics in the backend though custom resources exist
```
# HELP kube_scheduling_volcano_sh_v1beta1_PodGroup_creation_timestamp Creation time of PodGroup
# TYPE kube_scheduling_volcano_sh_v1beta1_PodGroup_creation_timestamp gauge
EMPTY HERE
```

It seems the timestamps field is not supported yet, could anyone help clarify further?

**Why is this needed**:
The ability to expose the creationTimestamp of Custom Resource with the capability from #1710

**Describe the solution you'd like**

**Additional context**
