### ISSUE TITLE
custom-resource-state-config-file could not open if mounted via config-map

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes/kube-state-metrics#1770]
**What happened**:

When running `KSM` with the distroless container and mount a configmap for the `customResourceStateConfigFile` KSM will fail with error `no such file or directory`

**What you expected to happen**:

`KSM` should read the content of the file.

**How to reproduce it (as minimally and precisely as possible)**:

For better understanding, i created a patched version of `main.go`

```diff
index 60db8908..c372f31b 100644
--- a/main.go
+++ b/main.go
@@ -70,6 +70,29 @@ func resolveCustomResourceConfig(opts *options.Options) (customresourcestate.Con
        if s := opts.CustomResourceConfig; s != "" {
                return yaml.NewDecoder(strings.NewReader(s)), true
        }
+       workdir, err := os.Getwd()
+       if err != nil {
+               klog.Fatal(err)
+       }
+       klog.Info(workdir)
+
+       dirname := "/data"
+
+       f, err := os.Open(dirname)
+       if err != nil {
+               klog.Fatal(err)
+       }
+       files, err := f.Readdir(-1)
+       f.Close()
+       if err != nil {
+               klog.Fatal(err)
+       }
+
+       for _, file := range files {
+               klog.Info(file.Name())
+               klog.Info(file.Mode())
+       }
+
        if file := opts.CustomResourceConfigFile; file != "" {
                f, err := os.Open(file)
                if err != nil {
```

which will log following additional output:

```
I0629 07:59:13.274545       1 main.go:77] /                       
I0629 07:59:13.274584       1 main.go:92] config.yaml                           
I0629 07:59:13.274588       1 main.go:93] Lrwxrwxrwx                                                                                                            
I0629 07:59:13.274597       1 main.go:92] ..data                                                                                                                
I0629 07:59:13.274601       1 main.go:93] Lrwxrwxrwx                            
I0629 07:59:13.274606       1 main.go:92] ..2022_06_29_07_59_06.1210452815                                                                                      
I0629 07:59:13.274612       1 main.go:93] drwxr-xr-x                                                                                                            
F0629 07:59:13.274619       1 main.go:99] lstat "/data/config.yaml": no such file or directory                                                                  
goroutine 1 [running]:                                                          
```

After that, i've tried following ugly patch

```diff
        if file := opts.CustomResourceConfigFile; file != "" {
-               f, err := os.Open(file)
+               fileInfo, err := os.Lstat(file)
                if err != nil {
                        klog.Fatal(err)
                }
-               return yaml.NewDecoder(f), true
+               if fileInfo.Mode()&os.ModeSymlink != 0 {
+                       klog.Info("symlink")
+                       originFile, err := os.Readlink(fileInfo.Name())
+                       klog.Info("origin file")
+                       klog.Info(originFile)
+                       f, err := os.Open(originFile)
+                       if err != nil {
+                               klog.Fatal(err)
+                       }
+                       return yaml.NewDecoder(f), true
+               } else {
+                       klog.Info("no symlink")
+                       f, err := os.Open(file)
+                       if err != nil {
+                               klog.Fatal(err)
+                       }
+                       return yaml.NewDecoder(f), true
+               }
+
        }
        return nil, false
```

but KSM failed again by doing

```go
		fileInfo, err := os.Lstat(file)
		if err != nil {
			klog.Fatal(err)
		}
```

pod spec looks like following

```yaml
    spec:
      containers:
      - args:
        - --custom-resource-state-config-file="/data/config.yaml"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: cluster-api-monitoring
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: cluster-api-monitoring
        name: config
```

When creating KSM container with following patched version

```diff
diff --git a/Dockerfile b/Dockerfile
index ae9ea350..6e5394ce 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,10 +8,11 @@ COPY . /go/src/k8s.io/kube-state-metrics/
 
 RUN make build-local
 
-FROM gcr.io/distroless/static:latest-${GOARCH}
+#FROM gcr.io/distroless/static:latest-${GOARCH}
+FROM alpine
 COPY --from=builder /go/src/k8s.io/kube-state-metrics/kube-state-metrics /
```

I get the same errors. But when i change the `command` arg in the pod-spec ksm is working fine

```yaml
            command:
            [
              "sh",
              "-c",
              '/kube-state-metrics --custom-resource-state-config-file="/data/config.yaml"',
            ]
```

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:
