### ISSUE TITLE
Custom resources are ignored when '--resources' argument is not empty

### ISSUE THREAD

**Issue by gadisn** [kubernetes/kube-state-metrics#1779]
**What happened**:
Trying to add metrics for custom resources doesn't work when the '--resources' argument is not empty.
I'm able to get metrics when '--resources' **is** empty.

**What you expected to happen**:
I would like to be able to use the combination of '--resources' and custom resources.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add custom resources as described in the docs, and then toggle the '--resources' argument

**Anything else we need to know?**:
I suspect that the problem is in https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/app/server.go#L92-L102.
Note that 'factories' are added to 'resources' only if 'opts.Resources' is zero.

**Environment**:
- kube-state-metrics version: v2.5.0
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: AWS
- Other info:

**Comment by gadisn** [comment]
Thanks @bavarianbidi for the quick answer.
So just to be sure - it is by design that CRDs are ignored when `--resources` isn't empty? KSM doesn't want allow adding both CRD AND specify resources?

**Comment by bavarianbidi** [comment]
hi @gadisn the behavior is not specific to CRDs.

> So just to be sure - it is by design that CRDs are ignored when `--resources` isn't empty? 
if `--resources` isn't empty the assumption is, that the user defines the targets for `KSM` via this flag.

> KSM doesn't want allow adding both CRD AND specify resources?
KSM support adding both. if `--resources` is empty all known resources will be set (even the resources which got generated from your `custom-resource-state-config`.

If `--resources` isn't empty, you have to specify each resource, e.g. `--resources=nodes,pods,<resource_from_your_custom_resource_state_config>`.

Could you share the content of your `custom-resource-state-config` and your current defined `--resources` arguments?

**Comment by gadisn** [comment]
Ah, got it, I was missing the fact that I need to add my CRD names also in `--resources` (I only added them with `--custom-resource-state-config`).
For reference, here are the CRD def and resources (partly obfuscated):
```
         --custom-resource-state-config
         |
          spec:
            resources:
              - groupVersionKind:
                  group: "a.b.c"
                  kind: "API"
                  version: "v1alpha1"
                metrics:
                  - name: "apiStatusMessage"
                    help: "hello help"
                    each:
                      path: [metadata, generation]
                    labelsFromPath:
                      hostPrefix: [spec, source, hostPrefix]
                      firstConditionMessage: [status, conditions, "0", message]
```
					  
` --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
`
