### ISSUE TITLE
Custom Resource configuration doesn't work

### ISSUE THREAD

**Issue by ikarlashov** [kubernetes/kube-state-metrics#1782]
**What happened**: Providing either `--custom-resource-state-config` or `--custom-resource-state-config-file` with correct values is not producing metric in prometheus.

**What you expected to happen**: having defined metric in prometheus

**How to reproduce it (as minimally and precisely as possible)**: Follow documentation for custom-resource-state-config.

**Environment**:
- kube-state-metrics version: 2.5.0
- Kubernetes version (use `kubectl version`): v1.22.9-eks-a64ea69
- Cloud provider or hardware configuration: AWS
- KSM is part of kube-prometheus stack
---
I tried `--custom-resource-state-config`:
```
- --custom-resource-state-config
- |
    spec:
      resources:
        - groupVersionKind:
            group: monitoring.coreos.com
            kind: "Prometheus"
            version: "v1"
          namespace: monitoring
          subsystem: custom
          metrics:
            - name: "prometheus_replicas"
              help: "Prometheus replicas"
              each:
                path: [spec, replicas]
```
As well as `--custom-resource-state-config-file`:
```
kind: CustomResourceStateMetrics            
spec:
  resources:
    - groupVersionKind:
        group: monitoring.coreos.com
        kind: "Prometheus"
        version: "v1"
      namespace: monitoring
      subsystem: custom
      metrics:
        - name: "prometheus_replicas"
          help: "Prometheus replicas"
          each:
            path: [spec, replicas]
```
Example of CRD:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-stack-prometheus
  namespace: kube-system
spec:
...
  replicas: 3
...
```

Neither option produces metric `monitoring_custom_prometheus_replicas`. Was trying to follow doc as much as possible :)
PS. What is weird - I don't see anything in logs. Process is definitely taking `--custom-resource-state-config-file` into account. Because If I point flag to non-existing file - pod is turning to `Error` state complaining about non-existing file.
