### ISSUE TITLE
Remove Verticalpodautoscaler Collector (VPA)

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1790]
As we have now an implementation to collect metrics from Custom Resources,  we want to remove the VPA Collector in KSM v3.0

**Comment by ninlil** [comment]
I fully understand the argument to remove the VPA Collector, but it's not possible right now.

The values from the vpa-recommender looks like this:
```yaml
...
status:
  conditions:
  - lastTransitionTime: "2022-07-04T13:40:27Z"
    status: "True"
    type: RecommendationProvided
  recommendation:
    containerRecommendations:
    - containerName: main
      lowerBound:
        cpu: 25m
        memory: 262144k
      target:
        cpu: 25m
        memory: 262144k
      uncappedTarget:
        cpu: 25m
        memory: 262144k
      upperBound:
        cpu: 25m
        memory: 262144k
```

and the "25m" cant be converted to a value... will just result in this:
```
E0826 12:39:39.333864  925520 registry_factory.go:556] "kube_autoscaling_k8s_io_v1_verticalpodautoscaler_cpu_rec" err="[status,recommendation,containerRecommendations,0,target]: [cpu]: []: strconv.ParseFloat: parsing \"25m\": invalid syntax"
```

As I see it, either:
a) update the VPA Collector to apiVersion autoscaling.k8s.io/v1 (according to #1718 )
b) implement a parser/converter for values that can convert the measurement unit to a plain value.
