### ISSUE TITLE
Duplicate result when query from prometheus server

### ISSUE THREAD

**Issue by hieu29791** [kubernetes/kube-state-metrics#1798]
**What happened**:
- I deploy helm chart **kube-state-metrics** from **ArgoCD**, and when I query, it shows the duplicate result. Here is the image: 
![image](https://user-images.githubusercontent.com/10827875/182812918-b6d8aa17-587d-4e10-91d6-8da86163249b.png)
- The first result includes more labels than the second. 
- I guess the first one because I deployed it via ArgoCD, and the second is the original result of **kube-state-metrics**
- Because of that, whenever an alert fires to the slack channel, it sends two messages simultaneously.
- Here is the argoCD config:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging

  destination:
    server: PLACEHOLDER
    namespace: PLACEHOLDER

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Prune=true

  source:
    chart: kube-state-metrics
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.2.11

    helm:
      releaseName: kube-state-metrics

      valueFiles:
        - values.yaml
```
**What you expected to happen**:
- When I query, I just want only the second result shows up. So alert fires to the slack channel not to be duplicated.  

**How to reproduce it (as minimally and precisely as possible)**:
- I deploy prometheus stack and kube-state-metrics via ArgoCD
