### ISSUE TITLE
CRD metric with wrong 'kind' - pod can't start

### ISSUE THREAD

**Issue by gadisn** [kubernetes/kube-state-metrics#1820]
When having a typo in the 'kind' of a crd metric def, an error is thrown, and the entire pod can't be used.

**Won't it be better to just report the inappropriate kind in the log**, instead of breaking the entire metrics chain?

Example for wrong kind:
```
  resources:
    - groupVersionKind:
        group: myteam.io
        kind: "NonExistingKind"
```

The error is reported in https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/builder.go#L96
