### ISSUE TITLE
kube_pod_status_ready is 2s late than pod.condistions.Ready timestamp

### ISSUE THREAD

**Issue by qingguee** [kubernetes/kube-state-metrics#1830]
**What happened**:
Hello,
Because missing pod ready timestamp metrics, I am using kube_pod_status_ready to monitoring pod ready. 
I use http API query kube_pod_status_ready , then find the ready timestamp by go though the metrics data. When detect value is 1, then return the timestamp. 
But after double check the ready timestamp from "kubectl get po xxx -o yaml" , it seems the metrics status value is always 2s late than the real ready timestamp from pod condition Ready. 
 
For example,from "kubectl get po  <xxx_pod_name> -o yaml"
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-08T01:15:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-08T01:20:36Z"
    status: "True"
    type: Ready
```
Prometheus config, I am using 1s as scrape_interval. 
```
- job_name: kubernetes-service-endpoints
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
```
But from metrics result, I got below
```
],
        [
            1662600037,
            "0"
        ],
        [
            1662600038,    <<== This is the timestamp pod ready from kube_pod_status_ready 
            "1"
        ],
        [
            1662600039,
            "1"
        ],
```
I also checked the source code, looks like everything is correct. 
https://github.com/kubernetes/kube-state-metrics/blob/20ef8a759681c8ed263184f481f4b60686f300bd/internal/store/pod.go#L1299

**What you expected to happen**:
Is there a way to get ready timestamp more accurate? 
Because I need calculate the startup time for a pod, I will need to know when the pod become ready. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:
