### ISSUE TITLE
Add *_labels metrics for custom resource configurations

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/kube-state-metrics#1832]
**What would you like to be added**:

Allow to expose `*_labels` for Custom Resource configuration which behaves the same as `kube_*_labels` metrics.
This means it would also use the configured value for the flag `--metric-labels-allowlist` for filtering the exposed labels.

**Why is this needed**:

To have the same kind of features for custom resource metrics.

**Describe the solution you'd like**

One option would be to add a boolean for enabling the labels for a custom resource configuration, e.g. at the `Resource` struct level https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/customresourcestate/config.go#L42

**Additional context**

As of today it would require some custom configuration to expose something like that for a custom resource.

```yaml
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: myteam.io
        kind: "Foo"
        version: "v1"
      metrics:
        - name: "labels"
          each:
            type: Info
            info:
              labelsFromPath:
                label_foo: [metadata, labels, foo]
                label_bar: [metadata, labels, bar]
```
