### ISSUE TITLE
"LabelFromKey" not avaliable

### ISSUE THREAD

**Issue by hdxj-kaoy** [kubernetes/kube-state-metrics#1868]
`labelFromKey` does not work when I use the config below

`kube-state-metrics --port=8880 --telemetry-port=8881 --kubeconfig=/config --custom-resource-state-config-file=/crsm.yaml`

crsm.yaml
```
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: bbb
        kind: "xxx"
        version: "v1alpha1"
      labelsFromPath:
        name: [metadata, name]
      metrics:
        - name: "np"
          help: "xxx"
          each:
            type: Gauge
            gauge:
              path: [status, nodeProgress]
              # does not work
              labelFromKey: type
```

CR looks like:
```
apiVersion: bbb/v1alpha1
kind: xxx
  ...
  ...
  ...
status:
  np:
    key1: 100
    key2: 100
```

I got :
```
kube_bbb_v1alpha1_xxx_np{name="aaa"} 100
kube_bbb_v1alpha1_xxx_np{name="aaa"} 100
```
instead of 
```
kube_bbb_v1alpha1_xxx_np{name="aaa",type="key1"} 100
kube_bbb_v1alpha1_xxx_np{name="aaa",type="key2"} 100
```

After checking the source code and changing 

https://github.com/kubernetes/kube-state-metrics/blob/a3a509acdff1f525c3ca2ff76344d0cedafd8a60/pkg/customresourcestate/registry_factory.go#L156-L160

to

```
 return &compiledGauge{ 
 	compiledCommon: *cc, 
 	ValueFrom:      valueFromPath, 
 	NilIsZero:      m.Gauge.NilIsZero, 
	LabelFromKey:   m.Gauge.LabelFromKey,
 }, nil 
```
 I get the result I want.

I wonder whether this is intentional or there are other solutions that do not need to modify the source code.
