### ISSUE TITLE
Lower Case Kind in `CustomResourceStateMetrics`

### ISSUE THREAD

**Issue by hpsawant7887-lacer** [kubernetes/kube-state-metrics#1869]
Support for Lower-Case Kind in `CustomResourceStateMetrics` is not there in `kube-state-metrics` version`2.6.0`
I am using the helm-chart version `4.21.0` which uses ksm `2.6.0`
-->

**What happened**:
For following `CustomResourceStateMetrics` the metric that is being created is `kube_acme_cert_manager_io_v1_challenge_created_timestamp_seconds`

```
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: acme.cert-manager.io
        version: "v1"
        kind: "challenge"
      metrics:
        - name: created_timestamp_seconds
          help: "CertManager Challenge creation time in Unix Epoch format"
          each:
            type: Gauge
            gauge:
              path:
                - metadata
                - creationTimestamp
          labelsFromPath:
            name:
              - metadata
              - name
            dnsName:
              - spec
              - dnsName
            type:
              - spec
              - type
            namespace:
              - metadata
              - namespace
```

However we see error in logs

```
E1025 17:57:36.561264       1 reflector.go:489] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: expected gvk acme.cert-manager.io/v1, Kind=challenge, but watch event object had gvk acme.cert-manager.io/v1, Kind=Challenge
```

If we keep kind as `Challenge`, it has metric name as `kube_acme_cert_manager_io_v1_Challenge_created_timestamp_seconds` with `C` in upper-case.

**What you expected to happen**:
We expect `kind` in `CustomResourceStateMetrics` to be all lower case.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:
