### ISSUE TITLE
labelFromKey is just for Gauge, other types (eg. Info) don't have the attribute 

### ISSUE THREAD

**Issue by ningan123** [kubernetes/kube-state-metrics#1871]
**What would you like to be added**:
I need a labelFromKey for Info, not just Gauge.

**Why is this needed**:
If a CR (eg. Foo) is like this, 
```
kind: Foo
apiVersion: myteam.io/vl
metadata:
    annotations:
        bar: baz
        qux: quxx
    labels:
        foo: bar
    name: foo
spec:
    version: v1.2.3
    order:
        - id: 1
          value: true
        - id: 3
          value: false
    replicas: 1
status:
    phase: Pending
    active:
        type-a: 1   # focus on this
        type-b: 3   # focus on this
```
we can get the metric label using the following YAML:
```
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: myteam.io
        kind: "Foo"
        version: "v1"
      metrics:
        - name: "active"
          help: "Foo active"
          each:
            type: Gauge
            gauge:
              path: [status, active]
              labelFromKey: type
```
The output metrics are like this:
```
kube_xxx_active{type=type-a} 1
kube_xxx_active{type=type-b} 3
```

However, if a CR (eg. Foo) is like this:

```
kind: Foo
apiVersion: myteam.io/vl
metadata:
    annotations:
        bar: baz
        qux: quxx
    labels:
        foo: bar
    name: foo
spec:
    version: v1.2.3
    order:
        - id: 1
          value: true
        - id: 3
          value: false
    replicas: 1
status:
    phase: Pending
    active:
        type-a: running  # focus on this
        type-b: failed   # focus on this
```
Because the value of  "type-a" is not a number, we need to use Info, not Gauge.  How can I get a metric with the label "type=type-a"?

**Describe the solution you'd like**
1) I need a labelFromKey for Info to get a metric with the label "type=type-a"
2) I want to get the value of "type-a" to use as a label "state=running"

The expected YAML is like this:
```
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: myteam.io
        kind: "Foo"
        version: "v1"
      metrics:
        - name: "active"
          help: "Foo active"
          each:
            type: Info
            info:
              path: [status, active]
              labelFromKey: type
              labelsFromPath:
                state: [???]  # I don't know how to write it
```

The expected output metrics are like this:
```
kube_xxx_active{type=type-a, state=running} 1
kube_xxx_active{type=type-b, state=failed} 1
```

thanks~

**Additional context**

https://github.com/kubernetes/kube-state-metrics/issues/1871#tasklist-block-c3fa25cd-a3c7-40b3-866e-600682e70731
