### ISSUE TITLE
CRS metrics are hardcoded to "gauge" type

### ISSUE THREAD

**Issue by rexagod** [kubernetes/kube-state-metrics#1886]
**What happened**: CRS metrics are hard-coded to "gauge" as the their TYPE.

**What you expected to happen**: CRS metrics should be able to dynamically deduce the TYPE correctly.

**How to reproduce it (as minimally and precisely as possible)**: PTAL at the example below. 

**Anything else we need to know?**: Surfaced here: https://github.com/kubernetes/kube-state-metrics/pull/1880#discussion_r1016737747.

***
<details>
<summary>Input</summary>

```yaml
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "apps"
        version: "v1"
        kind: "Deployment"
      labelsFromPath:
        name: [metadata, name]
      metrics:
        - name: "test_metrics"
          help: "metrics for debugging"
          each:
            type: Info
            info:
              path: [metadata, annotations]
              labelFromKey: test
```

</details>

<details>
<summary>Output</summary>

```yaml
# HELP kube_crd_test_metrics metrics for debugging
# TYPE kube_crd_test_metrics gauge (<--)
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="deployment.kubernetes.io/revision",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-a",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-b",version="v1"} 2
# HELP kube_crd_test_metrics metrics for debugging
# TYPE kube_crd_test_metrics gauge (<--)
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="deployment.kubernetes.io/revision",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-a",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-b",version="v1"} 2
```

</details>

***

**Environment**:
- kube-state-metrics version: HEAD
