### ISSUE TITLE
Do not collect  resources that start with ’kubernetes.io/‘

### ISSUE THREAD

**Issue by leason00** [kubernetes/kube-state-metrics#1939]
**What happened**:

my pod
```
limits:
        kubernetes.io/batch-cpu: 2k
        kubernetes.io/batch-memory: 4Gi
      requests:
         kubernetes.io/batch-cpu: "100"
         kubernetes.io/batch-memory: 819Mi
```
but not to be collected.

reason is  ’kubernetes.io/‘ Is considered to be a native resource:
https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/utils.go#L155

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:
