### ISSUE TITLE
reserved labels of CustomResourceStateMetrics are getting overwritten

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes/kube-state-metrics#1943]
**What happened**:

Contrary to the [current documentation](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md?plain=1#L52)

> NOTE: The `group`, `version`, and `kind` common labels are reserved, and will be overwritten by the values from the `groupVersionKind` field.

these fields won't get overwritten.

I have following configuration from [`cluster-api`](https://github.com/kubernetes-sigs/cluster-api/blob/5c345dd975b362cb4113294b6479700d79baa726/hack/observability/kube-state-metrics/crd-config.yaml#LL124-L134C19)

```yaml
    metricNamePrefix: capi_kubeadmcontrolplane
    metrics:
    - name: info
      help: Information about a kubeadmcontrolplane.
      each:
        info:
          labelsFromPath:
            version:
            - spec
            - version
        type: Info
```

but the generated metric will look like the following:

```
capi_kubeadmcontrolplane_info{cluster_name="glippy",group="controlplane.cluster.x-k8s.io",kind="KubeadmControlPlane",name="glippy",namespace="org-giantswarm",uid="bd2c772e-2140-480f-a051-3ecedc2ed02b",version="v1.22.7"}
```

**What you expected to happen**:

```
capi_kubeadmcontrolplane_info{cluster_name="glippy",group="controlplane.cluster.x-k8s.io",kind="KubeadmControlPlane",name="glippy",namespace="org-giantswarm",uid="bd2c772e-2140-480f-a051-3ecedc2ed02b",version="v1beta1"}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I've created https://github.com/kubernetes/kube-state-metrics/pull/1942 as an alternative approach for the auto-generated `group`,`version` and `kind` labels. I've also [created a tracking issue on `kubernetes-sigs/cluster-api`](https://github.com/kubernetes-sigs/cluster-api/issues/7832).

**Environment**:
- kube-state-metrics version: 2.7.0
- Kubernetes version (use `kubectl version`): 1.24.4
- Cloud provider or hardware configuration:
- Other info:
