### ISSUE TITLE
CustomResourceStateMetrics Gauges do not work for Kubernetes Controller Status Conditions

### ISSUE THREAD

**Issue by jan-kantert** [kubernetes/kube-state-metrics#1962]
**What happened**:
We are trying to export a metric based on the standard status conditions CRD for objects of our kubernetes controllers (i.e. cert-manager or custom controllers based on kubebuilder).

We defined `--custom-resource-state-config` in kube-state-metics 2.7.0:

```
      - --custom-resource-state-config
      # in YAML files, | allows a multi-line string to be passed as a flag value
      # see https://yaml-multiline.info
      -  |
          spec:
            resources:
            - groupVersionKind:
                group: xxxxx.xxx
                kind: "xxx"
                version: "v1"
              metrics:
              - name: "xxx_ready"
                help: "xxx ready state"
                each:
                  type: Gauge
                  gauge:
                    path: [status, conditions, "[type=Ready]", status]
```

Unfortunately, by default kubernetes controllers use a string condition:
```
status:
  conditions:
    - lastTransitionTime: "2019-10-22T16:29:31Z"
      status: "True"
      type: Ready
```

And `kube-state-metrics` yields a parse error:

```
registry_factory.go:589] \"kube_crd_xxxx_ready\" err=\"[status,conditions,[type=Ready],status]: []: strconv.ParseFloat: parsing \\\"True\\\": invalid syntax\""}
```

**What you expected to happen**:

I would expect it to be able to parse "True"/"False" or a way to map them to 1/0. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Install a controller which exposes status conditions in its CRD. For instance cert-manager would work.
2. Add the config line from above
3. Run kube-state-metrics

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.7.0
- Kubernetes version (use `kubectl version`): v1.22.17
- Cloud provider or hardware configuration: AWS via Kops
- Other info:

**Comment by jan-kantert** [comment]
I guess we need a case for "True" and "False" (probably also lower case) here: https://github.com/kubernetes/kube-state-metrics/blob/f01ce58a30d4bb2710bf3fbe2178aa3972e76508/pkg/customresourcestate/registry_factory.go#L630

**Comment by chrischdi** [comment]
In CAPI we do export conditions as `StateSet` this way ([source](https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/observability/kube-state-metrics/crd-config.yaml#L103-L120)):

```
    - name: status_condition
      help: The condition of a cluster.
      each:
        stateSet:
          labelName: status
          labelsFromPath:
            type:
            - type
          list:
          - 'True'
          - 'False'
          - Unknown
          path:
          - status
          - conditions
          valueFrom:
          - status
        type: StateSet
```

**Comment by jabdoa2** [comment]
> In CAPI we do export conditions as `StateSet` this way ([source](https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/observability/kube-state-metrics/crd-config.yaml#L103-L120)):
> 
> ```
>     - name: status_condition
>       help: The condition of a cluster.
>       each:
>         stateSet:
>           labelName: status
>           labelsFromPath:
>             type:
>             - type
>           list:
>           - 'True'
>           - 'False'
>           - Unknown
>           path:
>           - status
>           - conditions
>           valueFrom:
>           - status
>         type: StateSet
> ```

Looks like a valid workaround. Downside is probably twice (or 3x) the number of metrics and your queries become more complicated.

I guess another more generic way would be a valueMap for gauges. Could look like this:

```
  spec:
    resources:
    - groupVersionKind:
        group: xxxxx.xxx
        kind: "xxx"
        version: "v1"
      metrics:
      - name: "xxx_ready"
        help: "xxx status"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
            valueMap:
              'True': 1.0
              'False': 0.0
```

Not sure how many use cases exist for that kind of mapping though.
