### ISSUE TITLE
kube_pod_container_status_waiting_reason empty results

### ISSUE THREAD

**Issue by domcar** [kubernetes/kube-state-metrics#1982]
**What happened**:
Kube-state-metrics deployed via kube-stack-prometheus. Everything is working fine but the metric
"kube_pod_container_status_waiting_reason" is not available, or to be more precise, the metric itsself can be queried
but it's empty.

Also by looking at the metrics directly in the pod I can see they are empty:
```
# HELP kube_pod_container_status_waiting_reason Describes the reason the container is currently in waiting state.
# TYPE kube_pod_container_status_waiting_reason gauge
```
as you can see above the metric value is missing

**Anything else we need to know?**:
kube-state-metrics config:
```yaml
kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 500Mi
  metricLabelsAllowlist:
    - nodes=[*]
    - namespaces=[redacted]
```

**Environment**:
- kube-state-metrics version: 2.6.0
