### ISSUE TITLE
Can't watch custom resources with the same kind but different API groups

### ISSUE THREAD

**Issue by branden** [kubernetes/kube-state-metrics#2015]
This might be another duplicate of #1848, but I'm not sure if this behavior is covered by that issue.

**What happened**:

I ran kube-state-metrics with the following custom resource state config, which defines two metrics for two different resource kinds `Certificate` that belong to different API groups:

```yaml
spec:
  resources:
    - metricNamePrefix: kube_managedresource
      groupVersionKind:
        group: acm.aws.upbound.io
        version: v1beta1
        kind: Certificate
      commonLabels: {}
      labelsFromPath: {}
      metrics:
        - name: uid
          help: The UID of a acm.aws.upbound.io/v1beta1 Certificate.
          each:
            type: Info
            gauge: null
            stateSet: null
            info:
                labelsFromPath:
                    uid:
                        - metadata
                        - uid
                path: []
                labelFromKey: ""
          commonLabels: {}
          labelsFromPath: {}
          errorLogV: 0
      errorLogV: 0
      resourcePlural: certificates
    - metricNamePrefix: kube_managedresource
      groupVersionKind:
        group: acmpca.aws.upbound.io
        version: v1beta1
        kind: Certificate
      commonLabels: {}
      labelsFromPath: {}
      metrics:
        - name: uid
          help: The UID of a acmpca.aws.upbound.io/v1beta1 Certificate.
          each:
            type: Info
            gauge: null
            stateSet: null
            info:
                labelsFromPath:
                    uid:
                        - metadata
                        - uid
                path: []
                labelFromKey: ""
          commonLabels: {}
          labelsFromPath: {}
          errorLogV: 0
      errorLogV: 0
      resourcePlural: certificates
```

kube-state-metrics failed to start and logged the following error:

> "Parsing from Custom Resource State Metrics file failed" err="found multiple custom resource configurations for the same resource certificates"

**What you expected to happen**:

I expected kube-state-metrics to successfully parse the file and watch the different types.

**How to reproduce it (as minimally and precisely as possible)**:

Run kube-state-metrics with the above custom resource state config.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.7.0
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration:
- Other info:
