### ISSUE TITLE
CustomResourceStateMetrics Wildcard in paths

### ISSUE THREAD

**Issue by codysmithd** [kubernetes/kube-state-metrics#2057]
**What would you like to be added**:
Ability to wildcard parts of paths for `CustomResourceStateMetrics`, in this case specifically a `StateSet` path, but could equally apply to other paths.

**Example:**

_Custom Resource_
```yaml
status:
    foos:
    - name: "a"
      conditions:
      - type: "MetricForThis"
        color: "green"
    - name: "b"
    - name: "c" 
      conditions:
      - type: "MetricForThis"
        color: "yellow" 
```

We want to report a StateSet metric for the color of foos that have a condition of type "MetricForThis".

_Config_
```yaml
metrics:
  - name: my_metric
    each:
      type: StateSet
    stateSet:
      labelName: color
      path: [status, foos, "[name=*]", "conditions", "[type=MetricForThis]", color]
      list: [green, yellow, red]
```
`[name=*]` means "any" name where the following path conditions still apply. To differentiate matching instances, the value of the wildcard is also applied as a label.

_Metric output_
```
my_metric{name="a", color="green"} 1
my_metric{name="a", color="yellow"} 0
my_metric{name="a", color="red"} 0

my_metric{name="c", color="green"} 0
my_metric{name="c", color="yellow"} 1
my_metric{name="c", color="red"} 0
```

Outside of the basic case presented here, ideally this would work with further levels nesting as well (multiple wildcards in the path).
