### ISSUE TITLE
Support for Unknown status condition in Custom Resources

### ISSUE THREAD

**Issue by EronWright** [kubernetes/kube-state-metrics#2070]
**What would you like to be added**:
Improve support for producing a gauge for the status conditions of a custom resource, when the condition status is `Unknown`.  Today, the data point cannot be produced due to a parse error:
```
[status,conditions]: [1]: [status]: strconv.ParseFloat: parsing \"Unknown\": invalid syntax
```
The gauge definition is:
```yaml
    - name: "foo_status"
      help: "status condition "
      each:
        type: Gauge
        gauge:
          path: [status, conditions]
          labelsFromPath:
            type: ["type"]
          valueFrom: ["status"]
```

**Why is this needed**:
This is needed to round out the support for status conditions.  `Unknown` is a legit status value and should be supported.

**Describe the solution you'd like**
it isn't totally clear what the gauge value should be. Here's a couple of options:
1. Don't report an error message and skip reporting the data point.  This means that `Unknown` would translate into the absence of a data point.
2. Consider adding a `valueMap` structure to map the status values to a numerical value, e.g.
```yaml
    - name: "foo_status"
      help: "status condition "
      each:
        type: Gauge
        gauge:
          path: [status, conditions]
          labelsFromPath:
            type: ["type"]
          valueFrom: ["status"]
          valueMap:
            - {from: "Unknown", to: 0}
            - {from: "True", to: 1}
            - {from: "False", to: 0}

```

**Comment by robbie-demuth** [comment]
I just ran into this issue and was able to workaround it by using a StateSet

```
- name: status_condition
  each:
    type: StateSet
    stateSet:
      path: [status, conditions]
      labelName: status
      valueFrom: [status]
      list: [True, False, Unknown]
      labelsFromPath:
        type: [type]
```
