### ISSUE TITLE
Custom resource stopped working with 2.9.2

### ISSUE THREAD

**Issue by remram44** [kubernetes/kube-state-metrics#2100]
**What happened**:

Updated from 2.8.2 to 2.9.2, kube-state-metrics does not start. Same configuration.

> `I0622 17:08:31.102616       1 server.go:198] "Used resources" resources=[daemonsets persistentvolumes volumeattachments virtualmachineinstances endpoints secrets horizontalpodautoscalers ingresses limitranges poddisruptionbudgets certificatesigningrequests namespaces nodes statefulsets configmaps pods replicationcontrollers storageclasses cronjobs replicasets resourcequotas services deployments mutatingwebhookconfigurations persistentvolumeclaims validatingwebhookconfigurations jobs networkpolicies]`
> `E0622 17:08:31.102649       1 wrapper.go:40] "Failed to run kube-state-metrics" err="failed to set up resources: resource virtualmachineinstances does not exist. Available resources: replicasets,secrets,storageclasses,networkpolicies,ingresses,jobs,mutatingwebhookconfigurations,pods,services,volumeattachments,endpointslices,endpoints,limitranges,poddisruptionbudgets,serviceaccounts,clusterroles,nodes,validatingwebhookconfigurations,namespaces,horizontalpodautoscalers,leases,resourcequotas,rolebindings,deployments,persistentvolumes,roles,statefulsets,persistentvolumeclaims,cronjobs,replicationcontrollers,configmaps,clusterrolebindings,daemonsets,ingressclasses,certificatesigningrequests"`

**What you expected to happen**:

No configuration change required between 2.8.2 and 2.9.2, since the changelog doesn't mention anything. Alternatively, a useful error message, not "resource does not exist" when it is listed in "Used resources".

**How to reproduce it (as minimally and precisely as possible)**:

Command line (running in-cluster):

```
--port=8080
--resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments,virtualmachineinstances
--custom-resource-state-config-file=/config/custom-resource-config.yaml
--telemetry-port=8081
```

`/config/custom-resource-config.yaml`:

```yaml
spec:
  resources:
    - groupVersionKind:
        group: kubevirt.io
        version: v1
        kind: VirtualMachineInstance
      labelsFromPath:
        namespace: [metadata, namespace]
        name: [metadata, name]
      metrics:
        - name: vmi_migration_method
          help: "Migration method: LiveMigration if only the instance's memory needs to be copied, or BlockMigration if some of the disks require copying"
          each:
            type: StateSet
            stateSet:
              labelName: migration_method
              path: [status, migrationMethod]
              list: [LiveMigration, BlockMigration]
        - name: vmi_conditions
          help: "VMI conditions"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: ["type"]
              valueFrom: ["status"]
        - name: vmi_last_migration
          help: "End timestamp of last migration"
          each:
            type: Gauge
            gauge:
              path: [status, migrationState, endTimestamp]
        - name: vmi_phase
          help: "VMI phase"
          each:
            type: StateSet
            stateSet:
              labelName: phase
              path: [status, phase]
              list: [Pending, Scheduling, Scheduled, Running, Succeeded, Failed, Unknown]
        - name: vmi_info
          help: "VirtualMachineInstance information"
          each:
            type: Info
            info:
              labelsFromPath:
                node_name: [status, nodeName]
```

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.9.2
- Kubernetes version (use `kubectl version`): 1.25.10
- Cloud provider or hardware configuration: kubeadm Linux amd64
