### ISSUE TITLE
CustomResource: no metrics if no resource exists for CRD when ksm starts

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/kube-state-metrics#2142]
**What happened**:

There are two issues when no resources exist for a CRD at the time when kube-state-metrics starts:

1. If a resource for a custom resource gets created **after** kube-state-metrics starts:
	- no `HELP` or `TYPE` will get exported
2. In a special case, there will also no metrics get exported for it.

**What you expected to happen**:

* Not requiring a restart to expose the metrics

**How to reproduce it (as minimally and precisely as possible)**:

* Applied a CRD
* Started KSM with configuration for the CRD
* Sleep for 15s
* Created a CR of the above CRD type
* The metrics don't get exposed
* Restart KSM
* Metrics will get exposed

Used Configuration:

```yaml
# This file was auto-generated via: make generate-metrics-config
kind: CustomResourceStateMetrics
spec:
  resources:
  - groupVersionKind:
      group: cluster.x-k8s.io
      kind: Cluster
      version: v1beta1
    labelsFromPath:
      name:
      - metadata
      - name
      namespace:
      - metadata
      - namespace
      uid:
      - metadata
      - uid
    metricNamePrefix: capi_cluster
    metrics:
    - name: created
      help: Unix creation timestamp.
      each:
        gauge:
          path:
          - metadata
          - creationTimestamp
        type: Gauge
    - name: status_condition
      help: The condition of a cluster.
      each:
        stateSet:
          labelName: status
          labelsFromPath:
            type:
            - type
          list:
          - 'True'
          - 'False'
          - Unknown
          path:
          - status
          - conditions
          valueFrom:
          - status
        type: StateSet
```

Note: in this case: after creating the resource:

* The metric `capi_cluster_created` will get exposed, but no `HELP` or `TYPE`.
* The metric for `capi_cluster_status_condition` will not get exposed

**Anything else we need to know?**:

I think the issue got introduced in #1851

If the method `hasResources` which is called here:

https://github.com/kubernetes/kube-state-metrics/blob/cc06755239faf600cc3468737a321204a1432fcf/internal/store/builder.go#L548

get's changed to always return true instead of actually tring to list CRs:

https://github.com/kubernetes/kube-state-metrics/blob/cc06755239faf600cc3468737a321204a1432fcf/internal/store/builder.go#L627

it meets the expectation and metrics get exposed as soon as the first CR for the CRD gets created.

**Environment**:
- kube-state-metrics version: v2.9.2
- Kubernetes version (use `kubectl version`): v1.27.3
- Cloud provider or hardware configuration: kind
- Other info:
