### ISSUE TITLE
kube-state-metrics - write: broken pipe

### ISSUE THREAD

**Issue by jgagnon44** [kubernetes/kube-state-metrics#2261]
**What happened**:
After noticing some "anomaliles" in some metrics, did a little Googling and checked the kube-state-metrics pod log. Found numerous messages like the following:

```
E1205 05:04:35.900320       1 metrics_handler.go:223] "Failed to write EOF directive" err="write tcp 10.244.42.152:8080->10.244.101.147:35432: write: broken pipe"
E1205 05:05:37.269362       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write metrics family: write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
E1205 05:05:37.269391       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
E1205 05:05:37.269401       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
E1205 05:05:37.269410       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
E1205 05:05:37.269418       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
E1205 05:05:37.269425       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
E1205 05:05:37.269434       1 metrics_handler.go:223] "Failed to write EOF directive" err="write tcp 10.244.42.152:8080->10.244.101.147:40672: write: broken pipe"
```

**What you expected to happen**:
Not really sure, but I am sure these error messages are not good.

**How to reproduce it (as minimally and precisely as possible)**:

I am not sure how to reproduce this, as I don't know what causes it to occur. I found it in the pod logs, then decided to restart the pod. Unfortunately this blew away the old logs and it has yet to appear in the new pod logs.

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version:

I used the kube-prometheus-stack Helm chart (https://github.com/prometheus-community/helm-charts/) to install Prometheus, Grafana, etc. to our Kubernetes cluster. The Helm chart version is 52.1.0. After inspecting the Helm chart dependencies, I believe kube-state-metrics is version 5.14.0.

I did a quick inspection of the pod spec and found the following:

```
  containers:
    - name: kube-state-metrics
      image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.0
      args:
        - '--port=8080'
        - >-
          --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
```

* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.27) exceeds the supported minor version skew of +/-1
```

* Cloud provider or hardware configuration:

Our K8s cluster is an on-premises installation. The cluster nodes are running Ubuntu 20.04.

* Other info:

**Comment by bengoldenberg09** [comment]
@logicalhan any estimation when are you planning fixing it?
i face same issue with the same version.

`E0202 22:02:08.428816       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:41082: write: broken pipe"
E0205 04:56:32.728805       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write metrics family: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.728835       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.728857       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.728870       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.728888       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.928694       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.928740       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0205 04:56:32.928757       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:48750: write: connection reset by peer"
E0207 09:31:40.528764       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write metrics family: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"
E0207 09:31:40.528815       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"
E0207 09:31:40.528829       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"
E0207 09:31:40.528848       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"
E0207 09:31:40.528861       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"
E0207 09:31:40.528875       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"
E0207 09:31:40.528894       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.11.31.68:8080->10.11.20.121:34628: write: broken pipe"`

**Comment by dgrisonnet** [comment]
I don't have any bandwidth to investigate right now.

@CatherineF-dev do you perhaps have some time to take a look at this?

**Comment by CatherineF-dev** [comment]
Ok

**Comment by CatherineF-dev** [comment]
@bengoldenberg09

Could you help provide detailed steps on reproducing this issue? Thx

**Comment by towolf** [comment]
We're also using VictoriaMetrics and see the same issue.  Scraping component is "VMAgent".

`image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.0`

**Comment by decipher27** [comment]
Facing the same issue, current KSM version: v2.8.2

Logs:
```Ruby
E0219 03:57:11.745859       1 metrics_handler.go:213] "Failed to write metrics" err="failed to write help text: write tcp 1xx.xxx.63.7:8080->1xx.168.34.xx:55444: write: broken pipe"
E0219 03:57:11.745869       1 metrics_handler.go:213] "Failed to write metrics" err="failed to write help text: write tcp 1xx.xxx.63.7:8080->1xx.168.34.xx:55444: write: broken pipe"
E0219 03:57:11.745878       1 metrics_handler.go:213] "Failed to write metrics" err="failed to write help text: write tcp 1xx.xxx.63.7:8080->1xx.168.34.xx:55444: write: broken pipe"
```

**Comment by naweeng** [comment]
I have been observing the same when there are a lot of pods in the cluster(over 5K). This works properly when the number of pods are lower(under 500).

**Comment by CatherineF-dev** [comment]
qq: could anyone help provide detailed steps to reproduce this issue? Thx!

**Comment by CatherineF-dev** [comment]
cc @bengoldenberg09, could you paste the deployment yaml again? The above code formatting messed up.

cc @naweeng, do you remember how to reproduce?

**Comment by CatherineF-dev** [comment]
This error is thrown from here https://github.com/kubernetes/kube-state-metrics/blob/v2.8.2/pkg/metricshandler/metrics_handler.go#L210-L215 with error `write: broken pipe`

```golang
        // w http.ResponseWriter
	for _, w := range m.metricsWriters {
		err := w.WriteAll(writer)
		if err != nil {
			klog.ErrorS(err, "Failed to write metrics")
		}
	}

```

**Comment by CatherineF-dev** [comment]
I feel this might be related to go version.  Could you try v2.9.0+ which uses golang 1.9? cc @naweeng

**Comment by bxy4543** [comment]
> I feel this might be related to go version. Could you try v2.9.0+ which uses golang 1.9? cc @naweeng

Building with go 1.19, still the same error @CatherineF-dev

**Comment by mrueg** [comment]
Can you check the scrape_duration_seconds for the job that scrapes it? If there's a broken pipe, the TCP/HTTP connection might get terminated early.

**Comment by CatherineF-dev** [comment]
@bxy4543, could you help reproduce with detailed steps?

**Comment by cody-amtote** [comment]
im seeing the same issue on our dev cluster (which is fairly large)

**Comment by bxy4543** [comment]
> Can you check the scrape_duration_seconds for the job that scrapes it? If there's a broken pipe, the TCP/HTTP connection might get terminated early.

scrape_duration_seconds{cluster="cluster-name",container="kube-state-metrics",endpoint="http",instance="xxx:8080",job="kube-state-metrics",namespace="vm",pod="victoria-metrics-k8s-stack-kube-state-metrics-847ddd64-splbf",prometheus="vm/victoria-metrics-k8s-stack",service="victoria-metrics-k8s-stack-kube-state-metrics"} 1.602

**Comment by bxy4543** [comment]
> @bxy4543, could you help reproduce with detailed steps?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: victoria-metrics-k8s-stack
    meta.helm.sh/release-namespace: vm
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.10.0
    helm.sh/chart: kube-state-metrics-5.12.1
  name: victoria-metrics-k8s-stack-kube-state-metrics
  namespace: vm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-k8s-stack
      app.kubernetes.io/name: kube-state-metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: victoria-metrics-k8s-stack
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/part-of: kube-state-metrics
        app.kubernetes.io/version: 2.10.0
        helm.sh/chart: kube-state-metrics-5.12.1
    spec:
      containers:
      - args:
        - --port=8080
        - --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
        image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: victoria-metrics-k8s-stack-kube-state-metrics
      serviceAccountName: victoria-metrics-k8s-stack-kube-state-metrics
      terminationGracePeriodSeconds: 30
```

@CatherineF-dev

**Comment by bxy4543** [comment]
> Can you check the scrape_duration_seconds for the job that scrapes it? If there's a broken pipe, the TCP/HTTP connection might get terminated early.

I found the cause of the problem:
Since some data could still be obtained, I did not check the target status. When I checked the target status, I found this error:
```
cannot read stream body in 1 seconds: the response from "http://xxx:8080/metrics" exceeds -promscrape.maxScrapeSize=16777216; either reduce the response size for the target or increase -promscrape.maxScrapeSize
```
So I expanded the vmagent parameter `promscrape.maxScrapeSize` (default is 16777216), and no more errors were reported

**Comment by bxy4543** [comment]
> Can you check the scrape_duration_seconds for the job that scrapes it? If there's a broken pipe, the TCP/HTTP connection might get terminated early.

I found the cause of the problem:
Since some data could still be obtained, I did not check the target status. When I checked the target status, I found this error:
```
cannot read stream body in 1 seconds: the response from "http://xxx:8080/metrics" exceeds -promscrape.maxScrapeSize=16777216; either reduce the response size for the target or increase -promscrape.maxScrapeSize
```
So I expanded the vmagent parameter `promscrape.maxScrapeSize` (default is 16777216), and no more errors were reported

**Comment by bxy4543** [comment]
> qq: where did you find this error log? Is it from prometheus?

I am using victoria-metrics, which I found out from the vmagent page target.

**Comment by CatherineF-dev** [comment]
@jgagnon44  @decipher27 @naweeng @towolf could you try the above solution `So I expanded the vmagent parameter promscrape.maxScrapeSize (default is 16777216), and no more errors were reported`?

If no issues, will close it.

**Comment by hanwangsf** [comment]
What's the equivalent of `vmagent parameter promscrape.maxScrapeSize` in [Prometheus](https://prometheus.io/docs/prometheus/latest/configuration/configuration/)? If it is `body_size_limit`, it's default to 0, which is no limit. I'm still having the same issue, let me know if you folks were able to implement such solution and see results.

**Comment by radramad** [comment]
Please reopen this issue. It occurs in Prometheus

**Comment by radramad** [comment]
We increased the scrape interval and also cpu/memory resource limit in kubestatemetrics. Now we are not seeing this error.

**Comment by bakito** [comment]
We are also facing this issue in a prometheus setup.
It happens only on one out of five clusters, where all 5 clusters are all clusters use the identical setup.

Increasing cpu/memory does not help in our case.

**Comment by Aracki** [comment]
Just adding this here, so maybe it helps someone.

We fixed this by defining resources for our KSM. The kube-prometheus-stack actually leaves KSM without resources defined by default. 

We never had issues before as it is really lightweight, but there are times when it lands on the Node with 100% CPU utilization. K8s scheduler will not care about pods without resources defined and also it's higher chances it will land on high util nodes.

**Comment by sidewinder12s** [comment]
Also ran into this on v2.16. Somewhat interesting was that the readiness probes continued to function since a restart of the pod fixed the issue.

**Comment by zsksy123** [comment]
The version of my kube-state-metrics image is v2.13.0. I want to upgrade it to v2.16.0 or v2.17.0. However, after the upgrade, the kube-state-metrics pod failed to start. The detailed information is as follows: 
```
Events: Type     Reason          Age               From               Message
----     ------          ----              ----               -------
Normal   Scheduled       48s               default-scheduler  Successfully assigned kube-prometheus/prometheus-kube-state-metrics-5b47cbdc75-bzh2p to bjm3
Normal  AddedInterface  48s               multus             Add eth0 [10.96.136.109/32] from k8s-pod-network
Normal  Pulling         48s               kubelet            Pulling image "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.16.0"
Normal  Pulled          43s               kubelet            Successfully pulled image "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.16.0" in 4.373568264s (4.373575548s including waiting) Normal   Created         43s               kubelet            Created container kube-state-metrics
Normal   Started         43s               kubelet            Started container kube-state-metrics
Warning  Unhealthy       8s (x4 over 38s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
```

**Comment by EldritchCrow** [comment]
Saw this at my job this week as well. Our VMs were undergoing OS updates, and it seems to have put kube-state-metrics in this sort of broken state.

In my case, I would not reasonably expect kube-state-metrics to gracefully handle weird behavior in the underlying host. However, I would expect it to eventually recover by redialing the TCP connection.

Is that a feasible fix to this issue? That is, instead of preventing the underlying error state, detecting it when it occurs and lifecycling the impacted TCP connection(s).

Edit: Adding context, the issue fixed itself when I did a `kubectl rollout restart deployment`, with the new pod coming up totally fine.

**Comment by EldritchCrow** [comment]
Just to update, we found the root cause of our issue.

We were using VerticalPodAutoscaler to manage the resource requests for kube-state-metrics, and an unrelated bug was causing VPA to schedule KSM with way too little CPU. Presumably, it saw these errors because the client (prometheus) was timing out, and the root cause had nothing to do with the errors we were seeing.

Also, my comment about resetting the TCP connection doesn't really make sense, it's a broken pipe on the server (KSM) writing to the http.ResponseWriter, so there's nothing to redial.

Other users commented on this thread noting that they also saw this issue under high load, so I am willing to bet there's a common cause there. Personally, I think it would be helpful if KSM handled the broken pipe error better by surfacing something that looks more like a client timeout, instead of just continuing to try and shove data into the HTTP response, but other than that I don't think there's anything to fix here.

**Comment by Krelion** [comment]
try to increase scrape timeout and body size for vmagent or another client

        # VMAgent
        vmagent:
          enabled: true
          spec:
            extraArgs:
              promscrape.maxScrapeSize: "100MB"
            scrapeInterval: 60s
            scrapeTimeout: 60s

you can check in grafana by query

```
count({__name__=~"kube_.*"})
```

<img width="2230" height="730" alt="Image" src="https://github.com/user-attachments/assets/cb1029b3-311e-4b8f-bbac-854342b8426d" />

**Comment by Zia-Adjust** [comment]
`broken pipe` issue is gone for me after doing the following changes. 
in case it help to someone. I've set `scrape_interval` `scrapeTimeout` and `max_scrape_size`  
`victoria-metrics-k8s-stack` helm chart version is `0.61.6`
which is using the following kube-state-metrics chart.
```
- name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 6.3.0
```
my this KSM version is on `2.17.0`
```
kube-state-metrics:
  enabled: true
  vmScrape:
    enabled: true
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: '{{ include "kube-state-metrics.name" (index .Subcharts "kube-state-metrics") }}'
          app.kubernetes.io/instance: '{{ include "vm.release" . }}'
      endpoints:
        - port: http
          honorLabels: true
          scrape_interval: 60s
          scrapeTimeout: 60s
          max_scrape_size: 100MB # bump max scrape size
          metricRelabelConfigs:
            - action: labeldrop
              regex: (uid|container_id|image_id)
      jobLabel: app.kubernetes.io/name
```
Also bump the CPU resource for vmagent
```
    resources:
      limits:
        cpu: "800m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "200Mi"
```
But following logs are still there 
```
metrics_handler.go:227] "Failed to write metrics" err="failed to write help text: write tcp x.x.x.x:8080->x.x.x.x:55282: write: connection reset by peer"
