### ISSUE TITLE
Parse Nested Arrays does not work

### ISSUE THREAD

**Issue by rajatvig** [kubernetes/kube-state-metrics#2368]
Have a custom CRD returning `conditions` under a nested structure like 

```yaml
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-04-05T16:27:15Z"
      message: References resolved
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2024-04-05T16:27:15Z"
      message: Accepted HTTPRoute
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: projectcontour.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: contour
      namespace: projectcontour
      sectionName: https
```

Using `StateSet` to parse with path `['status', 'parents', 'conditions']` but getting an error like

```
registry_factory.go:685] "gatewayapi_grpcroute_status" err="[status,parents,conditions]: expected value for path to be string, got <nil>" 
```

Is this supported?

**Comment by OscarLlamas6** [comment]
@rajatvig were you able to find any solution to this? I have the same scenario with HTTPRoute when trying to add a new series with status

**Comment by OscarLlamas6** [comment]
This is how I managed to make it work

```yaml
...
        - name: "status_condition"
          help: "status condition"
          each:
            type: Gauge
            gauge:
              path: [status, parents, 0, conditions]
              labelsFromPath:
                type: ["type"]
                reason: ["reason"]
              valueFrom: ["status"]
...
```

**Comment by Dentrax** [comment]
I hit the same case and ended up on this issue. I have case where I need to parse the following OAM manifest:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-oam-manifest
spec:
  policies:
    - type: override
      name: test-override
      properties:
        components:
          - type: test-component-type
            name: test-component
            properties:
              language: go
              image: registry.test.com/test-component:latest
            traits:
              - type: trait-1
                properties:
                  services:
                    - name: test-service
              - type: my-custom-trait
                properties:
                  foo: 1
                  bar: 2
                  baz:
                    baz-1:
                      qux: 1
                    baz-2:
                      qux: 2
                    baz-3:
                      qux: 3
```

Given minimal YAML example above, I'd like to parse (and select) the `my-custom-trait`'s key fields so that I can get `foo` and `bar`. If possible, I'd like to get also keys of the `baz` object. Due to limitation of nested-array parsing in the `CustomResourceStateMetrics`, I'm not sure if its possible. I'm looking forward to this feature!

**Comment by eskarlarehn** [comment]
Hi!

I'd like this for parsing out path and backendRefs from rules in HTTPRoutes. From the following resource I'd like to be able to get all paths and all backendRefs, without needing to know how many they are beforehand :') 

```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: example-name
  namespace: example-namespace
  labels:
    app: pretty-app
spec:
  parentRefs:
    - name: example-gateway
      namespace: example
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /example-service/endpoint-1
      - path:
         type: PathPrefix
         value: /example-service/endpoint-2
      backendRefs:
        - name: main-service-backend
          port: 80
       - name: other-service-backend
          port: 88

```

Maybe this could be done with a jsonPath? So to parse the above resource I'd do

```
url: ["spec", "rules", "matches", "[]", "path", "value"]
backend:  ["spec", "rules", "backendRefs", "[]", "name"]
```

Basically swapping out the indexing you currently support with "[]”.
