### ISSUE TITLE
Duplicate tolerations causing issue with prometheus >= 2.52.0

### ISSUE THREAD

**Issue by rgarcia89** [kubernetes/kube-state-metrics#2390]
**What happened**:
Starting with version 2.52.0, Prometheus introduced a mechanism to detect duplicate series during scraping. This can lead to error logs when kube-state-metrics scrapes metrics for deployments, particularly if there are duplicate entries within the toleration array.

prometheus debug logs:
```
ts=2024-05-13T19:21:09.190Z caller=scrape.go:1777 level=debug component="scrape manager" scrape_pool=serviceMonitor/monitoring/kube-state-metrics/0 target=https://10.244.5.6:8443/metrics msg="Duplicate sample for timestamp" series="kube_pod_tolerations{namespace=\"calico-system\",pod=\"calico-kube-controllers-75c647b46c-pg9cr\",uid=\"bf944c52-17bd-438b-bbf1-d97f8671bd6b\",key=\"CriticalAddonsOnly\",operator=\"Exists\"}"
ts=2024-05-13T19:21:09.207Z caller=scrape.go:1738 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitoring/kube-state-metrics/0 target=https://10.244.5.6:8443/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
```

There might be a need to deduplicate the toleration entries or add an index to entries with existing duplicates.

**How to reproduce it (as minimally and precisely as possible)**:

create the following deployment and look at the metrics produced by kube-state-metrics

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: something
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: nginx
      tolerations:
       - key: CriticalAddonsOnly
         operator: Exists
       - key: CriticalAddonsOnly
         operator: Exists
```

**Anything else we need to know?**:
Issue report I opened on the prometheus project https://github.com/prometheus/prometheus/issues/14089

**Environment**:

* kube-state-metrics version: 2.12.0
* Kubernetes version (use `kubectl version`): 1.27.9
* Cloud provider or hardware configuration: AKS
* Other info:
