### ISSUE TITLE
custom metrics for resources w/ group="" broken, e.g. Node

### ISSUE THREAD

**Issue by robbat2** [kubernetes/kube-state-metrics#2434]
**What happened**:
Custom metrics for resources where group is empty, e.g. `Node` resource do not work. This was a regression between v2.8.2 and v2.9.0

**What you expected to happen**:
Custom metrics should work even with an empty group.

**How to reproduce it (as minimally and precisely as possible)**:
Run kube-state-metrics v2.9.0, compare vs v2.8.2

```yaml
resources:
  - groupVersionKind:
      kind: Node
      version: v1
      group: ""
    labelsFromPath:
      node: [metadata, name]
    metricNamePrefix: demo
    metrics:
      - name: timestamp
        each:
          type: Gauge
          gauge:
            path: [metadata]
            valueFrom: [creationTimestamp]
```

Error:
```
"failed to resolve GVK" err="group is required in the defined GVK /v1, Kind=Node" gvk="_v1_Node"
```

This breakage was introduced accidently in https://github.com/kubernetes/kube-state-metrics/pull/1851

Specifically here:
https://github.com/kubernetes/kube-state-metrics/blob/dc86adec127688c7e02a71bb4d60b1f9f98f0f61/internal/discovery/discovery.go#L123-L125

**Anything else we need to know?**:
This was previously reported https://github.com/kubernetes/kube-state-metrics/discussions/2333

Rolling KSM back to v2.8.2 and the custom metric DOES work, but that's not an option in production environment due to the need for RBAC features introduced 

**Environment**:
* kube-state-metrics version: v2.10.1
* Kubernetes version (use `kubectl version`): v1.25.1
* Cloud provider or hardware configuration: private
* Other info:

Screenshot of the metrics working in v2.8.2:
![screenshot](https://github.com/kubernetes/kube-state-metrics/assets/373898/6ee90cbd-7f85-4e6f-ae6d-4f3b4caf04cd)
