### ISSUE TITLE
Some job metrics are missing if job has no conditions

### ISSUE THREAD

**Issue by DerRockWolf** [kubernetes/kube-state-metrics#2443]
**What happened**:
Some job metrics (`kube_job_status_failed`, `kube_job_complete`, `kube_job_failed`) are missing for `Job`s without conditions.

**What you expected to happen**:
Metrics are present regardless if conditions exist.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create this job
<details><summary>job.yaml</summary>
<p>

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - image: alpine
        name: test
        command:
          - "sh"
          - "-c"
        args:
          - sleep 5 && exit 1
      restartPolicy: Never
```

</p>
</details>  

2. Observe that the `.status` is missing a `conditions` objects (before the backoffLimit is reached)
3. Observe that e.g., the `kube_job_status_failed` metric is missing (`curl localhost:8080/metrics | grep kube_job_status_failed`)

**Anything else we need to know?**:

The reason for this bug is that the labels and values are only set within a for loop (if a condition of type `Failed` exists):

https://github.com/kubernetes/kube-state-metrics/blob/85d1423b5b896f4fbce8394afed20cfe17371251/internal/store/job.go#L222-L224

I can provide a fix that sets the value regardless if there are any condition with type `Failed`.

**Environment**:

* kube-state-metrics version: `v2.12.0` (master `85d1423`)
* Kubernetes version (use `kubectl version`): `v1.29.6`
* Cloud provider or hardware configuration: homelab
