### ISSUE TITLE
Support for VolumeSnapshot metrics

### ISSUE THREAD

**Issue by mnacharov** [kubernetes/kube-state-metrics#2489]
**What would you like to be added**:

Expose metrics for VolumeSnapshot and VolumeSnapshotContent objects:
https://kubernetes.io/docs/concepts/storage/volume-snapshots/
they are available since kubernetes v1.20

**Why is this needed**:

To see current `ReadyToUse` status of these resources and have alert when `ReadyToUse==false` too long

**Describe the solution you'd like**

Implement new metrics in addition to current [docs/metrics/storage](https://github.com/kubernetes/kube-state-metrics/tree/610918e/docs/metrics/storage) metrics

**Additional context**

**Comment by mweibel** [comment]
I'm +1 on that though I'm not sure how the policy of kube-state-metrics is regarding these kind of resources since it's a custom resource and AFAIK not always installed. 

To work around not having it, you can also declare it as a [custom resource to scrape by kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md):

Example when using helm:
```yaml
rbac:
  extraRules:
    - apiGroups:
        - "snapshot.storage.k8s.io"
      resources:
        - volumesnapshots
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - "snapshot.storage.k8s.io"
      resources:
        - volumesnapshots/status
      verbs:
        - get
customResourceState:
  enabled: true
  # Add (Cluster)Role permissions to list/watch the customResources defined in the config to rbac.extraRules
  config:
    spec:
      resources:
        - groupVersionKind:
            group: snapshot.storage.k8s.io
            version: "v1"
            kind: VolumeSnapshot
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: volumesnapshot_info
              help: "Information about volumesnapshot"
              each:
                type: Info
                info:
                  labelsFromPath:
                    readyToUse: [status, readyToUse]
                    restoreSize: [status, restoreSize]
```
