### ISSUE TITLE
`kube_ingress_tls` produces duplicate metrics for duplicate Ingress hosts

### ISSUE THREAD

**Issue by mmckeen** [kubernetes/kube-state-metrics#2550]
**What happened**:

For an Ingress with the following spec:

```
  ingressClassName: external
  rules:
  - host: foo.com
    http:
      paths:
      - foo
  - host: foo.com
    http:
      paths:
      - bar
  tls:
  - hosts:
    - foo.com
    - foo.com
    secretName: foo-secret
```

`kube-state-metrics` produces duplicate `kube_ingress_tls` metrics resulting in `Error on ingesting samples with different value but same timestamp` errors when Prometheus scrapes these metrics.

**What you expected to happen**:

Only a single metric is produced and kube-state-metrics de-duplicates on the `tls_host` label.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

N/A

**Environment**:

* kube-state-metrics version: 2.12.0
* Kubernetes version (use `kubectl version`): v1.28.13
* Cloud provider or hardware configuration: N/A
* Other info: N/A
