### ISSUE TITLE
duplicate timestamps in kube_job_status_failed metrics for retried Jobs

### ISSUE THREAD

**Issue by shlomitubul** [kubernetes/kube-state-metrics#2565]
**What happened**:
When Jobs failed and then succeeded and `failedJobsHistoryLimit` are more then 0 then `kube_job_status_failed`  will create  duplicate samples since `kube_job_status_failed` has no uniq label like job_pod.

**What you expected to happen**:
kube_job_* metrics or at least `kube_job_status_failed` metrics should have some unique label (can be job_pod or retry_index) so promethus doesn't reject the scrape.

**How to reproduce it (as minimally and precisely as possible)**:
create Job resource with `failedJobsHistoryLimit: 1`, and `backoffLimit: 2`, trigger the job and exit the pod, then trigger again and let it pass.

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version: 2.14.0  
* Kubernetes version (use `kubectl version`): v1.30.5-gke.1014003
* Cloud provider or hardware configuration: GKE
* Other info:

```[tasklist]
### Tasks
```

**Comment by shlomitubul** [comment]
@zoglam it re-produced everytime this is the cronjob I used:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: renovate-placer-engineering
        app.kubernetes.io/instance: renovate-placer-engineering
        app.kubernetes.io/name: renovate
    spec:
      backoffLimit: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: RENOVATE_CONFIG_FILE
              value: /usr/src/app/config.json
            - name: LOG_LEVEL
              value: INFO
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.open-telemetry:4318
            image: ghcr.io/renovatebot/renovate:39.8.0
            imagePullPolicy: IfNotPresent
            name: renovate
            resources:
              limits:
                memory: 3Gi
              requests:
                cpu: "1"
                memory: 3Gi
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 1000
          serviceAccount: renovate-sa
          serviceAccountName: renovate-sa
          terminationGracePeriodSeconds: 30
  schedule: '@hourly'
  successfulJobsHistoryLimit: 3
  suspend: false
```
we used Prometheus in each cluster that send metrics to mimir, the number of pods in each cron/job is 1, we don't allow/need cuncrruny, so once we trigger job and the main process for example and then let next one pass then we get this error
