### ISSUE TITLE
Does Custom Resource State Metrics support deep nested objects?

### ISSUE THREAD

**Issue by pbxqdown** [kubernetes/kube-state-metrics#2589]
We have a k8s object as follows. 

```
status:
    resourceCount:
      tenantA:
        hostGroupA:
          example.com/type1: 2
          example.com/type2: 2
          example.com/type3: 20
```
We would like to generate a metrics like `resourceCount{tenant=tenantA, hostGroup=hostGroupA, resourceType=type2} 2`.
Initially I tried to use `labelFromKey`, but it seems only supports one level of nesting. I have to statically specify path, and in  the last level use labelFromKey to generate metrics by resourceType.
```
metrics:
            - name: resourceCount
              each:
                type: Gauge
                gauge:
                  path: [status, resourceCount, tenantA, hostGroupA]
                  labelFromKey: resourceType
```
Wondering whether we can use labelFromKey for nested objects.
