### ISSUE TITLE
Need to add the required label from the array

### ISSUE THREAD

**Issue by bharathv195** [kubernetes/kube-state-metrics#2620]
```yaml
status:
  conditions:
    - lastTransitionTime: ''
      status: 'True'
      type: Ready
    - lastTransitionTime: ''
      status: 'True'
      type: BootstrapReady
    - lastTransitionTime: ''
      status: 'True'
      type: InfrastructureReady
    - lastTransitionTime: ''
      status: 'True'
      type: NodeHealthy
    - lastTransitionTime: ''
      status: 'True'
      type: PlanApplied
    - lastTransitionTime: ''
      status: 'True'
      type: Reconciled
```
Is there anyway to add the only required label from the above array to the custom resource state?. For example, I want the status from the above code  where "type = NodeHealthy" and the label should looks like node_healthy_status="True" ?
