### ISSUE TITLE
`kube_job_status_failed` and `kube_job_status_succeeded` both `1` for succeeded job with retries

### ISSUE THREAD

**Issue by alexanderlinne** [kubernetes/kube-state-metrics#2642]
**What happened**:
Both `kube_job_status_failed` and `kube_job_status_succeeded` are set to `1` for a job with `status.succeeded: 1`, `status.failed: 1` and condition `SuccessCriteriaMet` with `status: True`

**What you expected to happen**:
`kube_job_status_failed` set to `0` regardless of the number of failed attempts if the job succeeds

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the following job
<details>
<summary>job.yaml</summary>

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  podReplacementPolicy: TerminatingOrFailed
  template:
    spec:
      containers:
        - image: bitnami/kubectl:latest
          name: test
          command:
            - "sh"
            - "-c"
          args:
            - if [ $(kubectl get job test -o json | jq -r '.status.failed // 0') -eq 1 ]; then exit 0; else exit 1; fi
      restartPolicy: Never
```

</details>

2. Observe that the first run is failing and the second run is succeeding
3. Observe that both `kube_job_status_failed` and `kube_job_status_succeeded` are set to `1`

```bash
# An example: https://github.com/kubernetes/kube-state-metrics/issues/2223#issuecomment-1792850276
minikube start
...
go run main.go --custom-resource-state-only --custom-resource-state-config-file ksm-2223/custom-resource-config-file.yaml --kubeconfig ~/.kube/config
```

**Anything else we need to know?**:
It seems that this behaviour exists since #2485, where `kube_job_status_failed` is set to `1` without a `reason` when `status.failed != 0` and no `Failed` condition can be found.

**Environment**:

* kube-state-metrics version: 2.15.0
* Kubernetes version (use `kubectl version`): v1.31.3
* Cloud provider or hardware configuration: Azure AKS
* Other info:
