### ISSUE TITLE
Duplicate samples for customResourceState metrics when trying to find an element in a list by key=value

### ISSUE THREAD

**Issue by JackCheng01** [kubernetes/kube-state-metrics#2646]
**What happened**:

We installed [serverless](https://github.com/kyma-project/serverless?tab=readme-ov-file#install)https://github.com/[kyma-project/serverless](https://github.com/kyma-project/serverless?tab=readme-ov-file#install)?tab=readme-ov-file#install) in cluster and deployed below CR

function CR:
```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: jack-test
  name: jack-test
  namespace: default
spec:
  replicas: 1
  resourceConfiguration:
    function:
      profile: XS
  runtime: nodejs20
  source:
    inline:
      source: |-
        /*
        If you prefer mjs import/export syntax over cjs you need to specify
        'type': 'module'
        in the Function dependencies (package.json) and along with that change the import/export syntax to:
        import foo from 'foo'
        export function main(event, context) {
          //your logic using foo library
          return
        }
        */

        module.exports = {
          main: async function (event, context) {
            const message = `Hello World`
              + ` from the Kyma Function ${context["function-name"]}`
              + ` running on ${context.runtime}!`;
            console.log(message);
            return message;
          }
        }
status:
  buildResourceProfile: slow
  conditions:
  - lastTransitionTime: "2025-04-07T02:37:25Z"
    message: Deployment jack-test-tkql6 is ready
    reason: DeploymentReady
    status: "True"
    type: Running
  - lastTransitionTime: "2025-04-07T01:31:42Z"
    message: Job jack-test-build-4s69t finished
    reason: JobFinished
    status: "True"
    type: BuildReady
  - lastTransitionTime: "2025-04-07T01:30:46Z"
    message: ConfigMap jack-test-77zgn created
    reason: ConfigMapCreated
    status: "True"
    type: ConfigurationReady
  functionResourceProfile: XS
  podSelector: serverless.kyma-project.io/function-name=jack-test,serverless.kyma-project.io/managed-by=function-controller,serverless.kyma-project.io/resource=deployment,serverless.kyma-project.io/uuid=91ed0a40-7c03-4d37-835c-87363adfc4a6
  replicas: 1
  runtime: nodejs20
  runtimeImage: europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:1.7.2
```

We have below CustomResourceStateMetrics configured, according to KSM [doc](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md#path-syntax):

<img width="657" alt="Image" src="https://github.com/user-attachments/assets/9d64969d-487d-4c45-bf00-f276b4b323bb" />

```yaml
apiVersion: v1
data:
  config.yaml: |
    kind: CustomResourceStateMetrics
    spec:
      resources:
      - errorLogV: 0
        groupVersionKind:
          group: serverless.kyma-project.io
          kind: Function
          version: v1alpha2
        labelsFromPath:
          name:
          - metadata
          - name
          namespace:
          - metadata
          - namespace
        metrics:
        - commonLabels:
            type: ConfigurationReady
          each:
            gauge:
              labelsFromPath:
                reason:
                - reason
                type:
                - type
              nilIsZero: true
              path:
              - status
              - conditions
              - '[type=ConfigurationReady]'
              valueFrom:
              - status
            type: Gauge
          help: function condition
          name: function_condition
kind: ConfigMap
metadata:
  name: kube-state-metrics-customresourcestate-config
  namespace: kyma-system
```

Duplicated samples generated by kube-state-metrics:
```
# TYPE kube_customresource_function_condition gauge
kube_customresource_function_condition{customresource_group="serverless.kyma-project.io",customresource_kind="Function",customresource_version="v1alpha2",name="jack-test",namespace="default",reason="ConfigMapCreated",type="ConfigurationReady"} 0
kube_customresource_function_condition{customresource_group="serverless.kyma-project.io",customresource_kind="Function",customresource_version="v1alpha2",name="jack-test",namespace="default",reason="ConfigMapCreated",type="ConfigurationReady"} 0
kube_customresource_function_condition{customresource_group="serverless.kyma-project.io",customresource_kind="Function",customresource_version="v1alpha2",name="jack-test",namespace="default",reason="ConfigMapCreated",type="ConfigurationReady"} 0
kube_customresource_function_condition{customresource_group="serverless.kyma-project.io",customresource_kind="Function",customresource_version="v1alpha2",name="jack-test",namespace="default",reason="ConfigMapCreated",type="ConfigurationReady"} 0
kube_customresource_function_condition{customresource_group="serverless.kyma-project.io",customresource_kind="Function",customresource_version="v1alpha2",name="jack-test",namespace="default",reason="ConfigMapCreated",type="ConfigurationReady"} 1
```

**What you expected to happen**:
Single sample generated by kube-state-metrics:
```
kube_customresource_function_condition{customresource_group="serverless.kyma-project.io",customresource_kind="Function",customresource_version="v1alpha2",name="jack-test",namespace="default",reason="ConfigMapCreated",type="ConfigurationReady"} 1
```

**How to reproduce it (as minimally and precisely as possible)**:

function.yaml
```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: jack-test
  name: jack-test
  namespace: default
spec:
  replicas: 1
  resourceConfiguration:
    function:
      profile: XS
  runtime: nodejs20
  source:
    inline:
      source: |-
        /*
        If you prefer mjs import/export syntax over cjs you need to specify
        'type': 'module'
        in the Function dependencies (package.json) and along with that change the import/export syntax to:
        import foo from 'foo'
        export function main(event, context) {
          //your logic using foo library
          return
        }
        */

        module.exports = {
          main: async function (event, context) {
            const message = `Hello World`
              + ` from the Kyma Function ${context["function-name"]}`
              + ` running on ${context.runtime}!`;
            console.log(message);
            return message;
          }
        }
```

custom-resource-state-config.yaml 
```yaml
kind: CustomResourceStateMetrics
spec:
  resources:
  - errorLogV: 0
    groupVersionKind:
      group: serverless.kyma-project.io
      kind: Function
      version: v1alpha2
    labelsFromPath:
      name:
      - metadata
      - name
      namespace:
      - metadata
      - namespace
    metrics:
    - commonLabels:
        type: ConfigurationReady
      each:
        gauge:
          labelsFromPath:
            reason:
            - reason
            type:
            - type
          nilIsZero: true
          path:
          - status
          - conditions
          - '[type=ConfigurationReady]'
          valueFrom:
          - status
        type: Gauge
      help: function condition
      name: function_condition
```

```bash
# An example: https://github.com/kubernetes/kube-state-metrics/issues/2223#issuecomment-1792850276
minikube start
# install kyma serverless module as explained here: https://github.com/[kyma-project/serverless](https://github.com/kyma-project/serverless?tab=readme-ov-file#install)?tab=readme-ov-file#install
# apply functions.yaml
...
go run main.go --custom-resource-state-only --custom-resource-state-config-file=custom-resource-state-config.yaml  --kubeconfig=~/.kube/config
```

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version: v2.15.0
* Kubernetes version (use `kubectl version`): v1.32.2
* Cloud provider or hardware configuration: N/A
* Other info: https://github.tools.sap/kyma/backlog/issues/7049

**Comment by JackCheng01** [comment]
After some experiment, seems this is not a bug from KSM, we need to update our config to something like:
```yaml
        each:
          type: Gauge
          gauge:
            path: [status, conditions, "[type=ConfigurationReady]", status]
            labelsFromPath:
              reason: [reason]
```
