### ISSUE TITLE
Why service-endpoint scraping instead of pod scraping with Prometheus?

### ISSUE THREAD

**Issue by cmur2** [kubernetes/kube-state-metrics#312]
In the [Kubernetes Deployment section in your README](https://github.com/kubernetes/kube-state-metrics/blob/master/README.md#kubernetes-deployment) you state that kube-state-metrics should be setup using a Kubernetes deployment and service as example. Prometheus will scrape it automatically if the service-endpoints scraping is properly configures.

Now I wonder why kube-state-metrics needs a Kubernetes service besides the deployment and why not just scrape the kube-state-metrics pod(s) directly using the following YAML snippet in the deployment:

```yaml
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
```

I found a [thread on the Prometheus Users mailing list](https://groups.google.com/forum/#!topic/prometheus-users/jDEzVHUUFzw) where the consensus seems to be:

> An important distinction is for Pods that don't have any corresponding Services - they won't be scraped by the endpoints job, but will be by the pods job.  If you ever find yourself adding a Service just to collect metrics, you might consider scraping pods instead.

What is your stance on that case?
