### ISSUE TITLE
Some metrics are not reporting all namespaces

### ISSUE THREAD

**Issue by saady** [kubernetes/kube-state-metrics#339]
kube_pod_container_resource_requests_cpu_cores and kube_pod_container_resource_requests_memory_bytes  only reporting few namespaces pods containers cpu and memory usage.

  Deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
        version: "v1.1.0"
    spec:
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:v1.1.0
        command: ["/kube-state-metrics", "--port=8080", "--collectors=deployments,daemonsets,jobs,limitranges,nodes,pods,replicasets,replicationcontrollers,resourcequotas,services,statefulsets,persistentvolumeclaims"]
        ports:
        - containerPort: 8080
```

Service

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
  selector:
    app: kube-state-metrics
```
