### ISSUE TITLE
NodeNetworkUnavailable missing from kube_node_status_condition

### ISSUE THREAD

**Issue by r4j4h** [kubernetes/kube-state-metrics#405]
According to the Changelog version [1.0.0-rc1](https://github.com/kubernetes/kube-state-metrics/blob/aaf8e2fa716010762a30d675e06fdcb68f942040/CHANGELOG.md#v100-rc1--2017-08-02) several metrics, including `kube_node_status_network_unavailable`, were collapsed into the metric `kube_node_status_condition`.

Initially reported in #258, `NodeNetworkUnavailable` [exists in this project's tests](https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/node_test.go#L206) but in my instances of kube-state-metrics the condition="NetworkUnavailable" never appears.

It seems like it was intended for this to be present through the new metric but a regression was introduced around the `kube_node_status_condition` merger so this Issue is about restoring it.

I send my metrics into Prometheus, the following PromQL query:

`sum by(condition) (kube_node_status_condition{job="metrics/prometheus-kube-state-metrics"})`

results in:

```
{condition="MemoryPressure"} | 10
{condition="OutOfDisk"} | 10
{condition="Ready"} | 10
{condition="DiskPressure"} | 10
```

Based on conversation in #258 this may be from upstream Kubernetes getting rid of the metric and kube-state-metrics simply relaying what Kubernetes gives. If that is the case, then the test code is indeed just from the legacy days when it was provided and could be replaced with a current one like OutOfDisk or just left as is, letting these issues inform anyone in the future of what happened.

I am thinking this is likely the case as my nodes give the following statuses:

```
status:
  conditions:
  - lastHeartbeatTime: 2018-03-23T23:50:08Z
    lastTransitionTime: 2018-03-23T14:04:28Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2018-03-23T23:50:08Z
    lastTransitionTime: 2018-03-23T14:04:28Z
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: 2018-03-23T23:50:08Z
    lastTransitionTime: 2018-03-23T14:04:28Z
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: 2018-03-23T23:50:08Z
    lastTransitionTime: 2018-03-23T14:04:48Z
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
```

Notably all those reported from my kube-state-metrics are present, but networking is not.

So things likely are working as intended, but I wanted to submit this Issue for closure on the matter from #258 because I let it go stale and don't have permissions to reopen it.
