### ISSUE TITLE
Applying CPU limits to kube-state-metrics causes rapid memory consumption

### ISSUE THREAD

**Issue by while1malloc0** [kubernetes/kube-state-metrics#461]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Applying CPU limits to a pod running kube-state-metrics with no namespace flag causes unbounded memory allocation. This continues until the pod is OOM-killed by Kubernetes. This seems to happen reliably whenever CPU limits are applied. With no CPU limits, or with the `--namespace` flag supplied, the pod stays well under its memory limit. I observed this by applying a limit, running `htop`, and watching the process memory grow until it is killed.

The particular cluster is fairly large. Running `kubectl get all --all-namespaces | wc -l` returns 1375, so it seems reasonable that quite a bit memory would have to be allocated, as explained in [this issue](https://github.com/kubernetes/kube-state-metrics/issues/257), but I can't seem to figure out why applying CPU limits would cause such rapid and unbounded memory allocation. 

**What you expected to happen**:
Memory allocation does not grow as rapidly. 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a Kubernetes Deployment containing CPU resource limits to a cluster. Here's the deployment file that I'm seeing this behavior with: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: quay.io/coreos/kube-state-metrics:v1.2.0
        ports:
        - name: http-metrics
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            # removing this CPU limit reliably solves memory limit issues
            cpu: 200m
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 4Gi
```

**Anything else we need to know?**

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-
27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Kube-state-metrics image version: I've reproduced this issue with v1.2.0 and v1.3.0
