### ISSUE TITLE
deployment state error

### ISSUE THREAD

**Issue by liuzhi1986** [kubernetes/kube-state-metrics#465]
When I create a deployment with 1 replicas. I got this:
```
kube-state-metrics-76cf49fd6f-k2z6j                          2/2       Running   0          11m       10.10.32.10     cn-hangzhou.i-bp10ebr5qg3ycsr8wq19
kube-state-metrics-7c7686879d-4d2bj                          0/2       Pending   0          11m       <none>          <none>
```
My yaml  file like this:
```
apiVersion: apps/v1beta2
# Kubernetes versions after 1.9.0 should use apps/v1
# Kubernetes versions before 1.8.0 should use apps/v1beta1 or extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: lzcy5151/kube-state-metrics:v1.2.0 
        ports:
        - name: http-metrics
          containerPort: 8080
        - name: telemetry
          containerPort: 8081
        command: ["/kube-state-metrics", "--port=8080", "--telemetry-port=8081"]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
      - name: addon-resizer
        image: lzcy5151/addon-resizer-amd64:2.1
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        env:
          - name: MY_POD_NAME            valueFrom:
              fieldRef:                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE            valueFrom:
              fieldRef:                fieldPath: metadata.namespace
        command:          - /pod_nanny
          - --container=kube-state-metrics

```
I try to delete and recreate the deployment or delete the Pending pod, but the pending pod still here.
