### ISSUE TITLE
Jobs reported as restarted in kube_pod_container_status_restarted_total

### ISSUE THREAD

**Issue by jpds** [kubernetes/kube-state-metrics#478]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I have a series of cron jobs in Kubernetes, and the following Prometheus rule (taken from here[1]):

```
- alert: PodFrequentlyRestarting
  expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
  for: 10m
  labels:
    severity: warning
  annotations:
    description: Pod {{$labels.namespace}}/{{$labels.pod}} was restarted {{$value}} times within the last hour
    summary: Pod is restarting frequently
```

My jobs spin up, and are fine:

```
$ kubectl get pods -n production-app -w
...
job1-1528893000-pmdxv      0/1       Completed   0          28m
job1-1528804800-vphrp    0/1       Completed   0          1d
job1-1528848000-cg4zn    0/1       Completed   0          12h
job2-1528848000-rnzmg   0/1       Completed   0          12h
job2-1528869600-qqwxd   0/1       Completed   0          6h
...
```

For some reason, alerts for this metric fire even those none of the pods have restarted and all is fine.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Kube-state-metrics image version: 1.3.1

[1]: https://github.com/poseidon/typhoon/blob/0764bd30b5682931ab50348fedfee72798965c51/addons/prometheus/rules.yaml#L296
