### ISSUE TITLE
NodeInfo Metric

### ISSUE THREAD

**Issue by Nalum** [kubernetes/kube-state-metrics#53]
I think it is worth adding the Node IP address to the NodeInfo metric but I'd like feedback on if the public, private or both (or all if there is more than the 2) should be added as labels?

This is the structure I see when I get a node and out put as yaml:
```
status:
  addresses:
  - address: X.X.X.X
    type: InternalIP
  - address: X.X.X.X
    type: ExternalIP
```

I'm happy to create a PR for this if it is something you think would be good to have and if I can get that bit of direction.
