### ISSUE TITLE
metric: kube_pod_container_status_waiting_reason missing label reason="CrashLoopBackOff" and reason="ImagePullBackOff"

### ISSUE THREAD

**Issue by tasdikrahman** [kubernetes/kube-state-metrics#547]
** BUG REPORT **:

/kind bug

**What happened**:

I recently upgraded 
- kube-state-metrics from version `1.2.0` to `1.4.0` 
- addon-resizer from version `1.0` to `1.7`

**What you expected to happen**:

On my older k8s cluster (v1.8.9+coreos.0), where I have made the same upgrade. I can see the metric 

```
kube_pod_container_status_waiting_reason{container="traefik-ingress-lb",namespace="kube-system",pod="traefik-ingress-controller-qhzwn",reason="ErrImagePull"} 0
kube_pod_container_status_waiting_reason{container="traefik-ingress-lb",namespace="kube-system",pod="traefik-ingress-controller-qhzwn",reason="ImagePullBackOff"} 0
kube_pod_container_status_waiting_reason{container="traefik-ingress-lb",namespace="kube-system",pod="traefik-ingress-controller-sjbxf",reason="ContainerCreating"} 0
kube_pod_container_status_waiting_reason{container="traefik-ingress-lb",namespace="kube-system",pod="traefik-ingress-controller-sjbxf",reason="CrashLoopBackOff"} 0
```

being emitted, but on my newer k8s cluster(v1.9.4+coreos.0), I can't see the label `reason="CrashLoopBackOff"` being added to the metric `kube_pod_container_status_waiting_reason`. 

```
kube_pod_container_status_waiting_reason{container="node-exporter",namespace="monitoring",pod="node-exporter-zdzxf",reason="ContainerCreating"} 0
kube_pod_container_status_waiting_reason{container="node-exporter",namespace="monitoring",pod="node-exporter-zdzxf",reason="ErrImagePull"} 0
kube_pod_container_status_waiting_reason{container="node-exporter",namespace="monitoring",pod="node-exporter-zfbdt",reason="ContainerCreating"} 0
kube_pod_container_status_waiting_reason{container="node-exporter",namespace="monitoring",pod="node-exporter-zfbdt",reason="ErrImagePull"} 0
```

where the labels `CrashLoopBackOff` and `ImagePullBackOff ` are missing. The only thing which is different from the two clusters is the version of k8s 

**How to reproduce it (as minimally and precisely as possible)**:

deploy the below two manifest files on the respective k8s cluster versions to see the missing label on the metric `kube_pod_container_status_waiting_reason `

**Anything else we need to know?**:

manifest files for the two clusters

```
##  k8s cluster (v1.8.9+coreos.0)
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/kube-state-metrics
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-state-metrics
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.4.0
        imagePullPolicy: IfNotPresent
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: telemetry
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 116m
            memory: 132Mi
          requests:
            cpu: 116m
            memory: 132Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /pod_nanny
        - --container=kube-state-metrics
        - --cpu=100m
        - --extra-cpu=1m
        - --memory=100Mi
        - --extra-memory=2Mi
        - --threshold=5
        - --deployment=kube-state-metrics
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/google_containers/addon-resizer:1.7
        imagePullPolicy: IfNotPresent
        name: addon-resizer
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/node-ops: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-state-metrics
      serviceAccountName: kube-state-metrics
      terminationGracePeriodSeconds: 30
```

and the newer cluster would be

```
## v1.9.4+coreos.0
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/kube-state-metrics
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-state-metrics
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.4.0
        imagePullPolicy: IfNotPresent
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: telemetry
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 119m
            memory: 138Mi
          requests:
            cpu: 119m
            memory: 138Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /pod_nanny
        - --container=kube-state-metrics
        - --cpu=100m
        - --extra-cpu=1m
        - --memory=100Mi
        - --extra-memory=2Mi
        - --threshold=5
        - --deployment=kube-state-metrics
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/google_containers/addon-resizer:1.7
        imagePullPolicy: IfNotPresent
        name: addon-resizer
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-state-metrics
      serviceAccountName: kube-state-metrics
      terminationGracePeriodSeconds: 30
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.9 and 1.9.4
- Kube-state-metrics image version: 1.4.0
