### ISSUE TITLE
kube_pod_container_resource_requests reports for removed pod

### ISSUE THREAD

**Issue by estahn** [kubernetes/kube-state-metrics#559]
/kind bug

**What happened**:

Using the following PromQL we tried to see pod resource usage:
```
kube_pod_container_resource_requests{node="ip-10-10-123-123.ap-southeast-2.compute.internal",resource="cpu",container="foobar"}
```

The container doesn't exist on the host anymore but still reports a metric > 0.

**What you expected to happen**:

The gauge should go down to 0.

**How to reproduce it (as minimally and precisely as possible)**:

Just using the above example and by removing the pod/container.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): ```Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}```
- Kube-state-metrics image version: ```quay.io/coreos/kube-state-metrics:v1.4.0```

**Comment by mxinden** [comment]
@estahn thanks for the bug report.

I am facing difficulties reproducing this. I tried the following:

```bash
minikube start --kubernetes-version=v1.10.0 --memory=4096
~/go/src/k8s.io/kube-state-metrics
kubectl apply -f kubernetes/
kubectl port-forward -n kube-system   kube-state-metrics-c8bb4c85d-p94z9 8080
```

Then I created the following pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: wp
    image: wordpress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

and checked its metrics:
```bash
curl localhost:8080/metrics | grep frontend
```

Which returns the `kube_pod_container_resource_requests` metric.

After deleting the Pod, the above mentioned metric is gone.

Can you reproduce your bug in this way?
