### ISSUE TITLE
kube_pod_status_phase treats Completed pod as Running

### ISSUE THREAD

**Issue by juzhao** [kubernetes/kube-state-metrics#568]
/kind bug

**What happened**:
pods under openshift-infra project
NAME READY STATUS RESTARTS AGE
hawkular-cassandra-1-d9cq5 1/1 Running 0 5h
hawkular-cassandra-2-clwx8 1/1 Running 1 5h
hawkular-metrics-9l2ws 1/1 Running 0 5h
hawkular-metrics-schema-g2k48 0/1 Completed 1 5h
heapster-78gxb 1/1 Running 0 5h

hawkular-metrics-schema pod is created by cron job, and its status is Completed
queried
kube_pod_status_phase{phase="Running",namespace="openshift-infra"}
in prometheus UI.

it treats hawkular-metrics-schema-g2k48 status as Running, not Completed.
![image](https://user-images.githubusercontent.com/22743651/47434545-5c384e80-d7d5-11e8-8f81-6f449f410edf.png)

**What you expected to happen**:
Should treat Completed as Completed, not Running

**How to reproduce it (as minimally and precisely as possible)**:
As one simple test, we can create pod by job, when the job is finished, the pod's status will be changed to Completed

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-23T18:24:29Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-23T18:24:29Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
v1.4.0

**Comment by yagonobre** [comment]
I will send a pr with the fix later

**Comment by midN** [comment]
Same as https://github.com/kubernetes/kube-state-metrics/issues/584

Any news on that one @brancz ?

**Comment by brancz** [comment]
Can you share the pod json/yaml of a pod that you are seeing this with? I'm suspecting that it actually does say this and kube-state-metrics correctly exposes the metric based on whatever information it gets from Kubernetes about this.

**Comment by midN** [comment]
@brancz

**Comment by midN** [comment]
@brancz 
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-disabler
  namespace: X
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: X
            image: X
            imagePullPolicy: Always
            resources:
              requests:
                memory: "200Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
          restartPolicy: Never
```

Interestingly there are 3 pods with status Completed
```
➜  ~ (aws-prod:disable): kgp | grep forwarding-auto-disabler
irs-forwarding-auto-disabler-1542629100-rtqg5   0/1     Completed   0          1h
irs-forwarding-auto-disabler-1542632700-lrfk4   0/1     Completed   0          58m
irs-forwarding-auto-disabler-manual-sv5-ff4dg   0/1     Completed   0          3d
```

And all 3 are listed in kube-state-metrics with cpu_limits.
```
kube_pod_container_resource_limits_cpu_cores{container="disablecli",namespace="disable",node="x",pod="irs-forwarding-auto-disabler-1542629100-rtqg5"} 0.25
kube_pod_container_resource_limits_cpu_cores{container="disablecli",namespace="disable",node="xl",pod="irs-forwarding-auto-disabler-manual-sv5-ff4dg"} 0.25
kube_pod_container_resource_limits_cpu_cores{container="disablecli",namespace="disable",node="x",pod="irs-forwarding-auto-disabler-1542632700-lrfk4"} 0.25
```

I would have expected Completed pods not to show up as cpu limits here, that provides fake values for our monitoring in Datadog or Prometheus.
