### ISSUE TITLE
Wrong values in labels (taken from prometheus pod instead of application pod)

### ISSUE THREAD

**Issue by sta-szek** [kubernetes/kube-state-metrics#612]
/kind bug

Hi, first of all I tried to find solution but could not. Don't know if this is bug or feature but definitely stopped my work so I decided to ask for help. Is that correct repo for the issue?

**What happened**:
Metrics have values from prometheus pod / prometheus-prometheus-kube-state-metrics instead of application pod. Example:
```
{
app="prometheus",
chart="prometheus-5.0.1",
component="kube-state-metrics",
container="cloud-microservice-template",
heritage="Tiller",
instance="xxxxxxx:8080",
job="kubernetes-service-endpoints",
kubernetes_name="prometheus-prometheus-kube-state-metrics",
kubernetes_namespace="monitoring",
namespace="default",
pod="cloud-microservice-template-598556f97-xbr7q",
pod_label_app="prometheus",
pod_label_component="kube-state-metrics",
pod_label_maintainer_team="infrastructure",
pod_label_pod_template_hash="3455604768",
pod_label_release="prometheus",release="prometheus"
}
```
In above example only `container` and `pod` are correct. The `pod_label_maintainer_team` is taken from prometheus instead of cloud-microservice-template deployment and because of that I cannot do correct mappings.

**What you expected to happen**:
All label values will be taken from application pod

**How to reproduce it (as minimally and precisely as possible)**:
Run prometheus helm chart, configure kubernetes-service-endpoint job: 
```
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
          - role: endpoints

        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: pod_label_$1
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Kube-state-metrics image version
`k8s.gcr.io/kube-state-metrics:v1.1.0`
