### ISSUE TITLE
Add support for clusters using PodSecurityPolicy

### ISSUE THREAD

**Issue by idanlevin** [kubernetes/kube-state-metrics#622]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
When deploying to a cluster with PodSecurityPolicy enabled, the deployment fails to start with the following message:

```
message: 'pods "monitoring-kube-state-metrics-7d5d8f9446-" is forbidden: unable to validate against any pod security policy: []'
reason: FailedCreate
```

**What you expected to happen**:
The deployment should succeed

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster with PodSecurityPolicy enabled
2. Try to deploy the _kube-state-metrics_ application

**Anything else we need to know?**:
This can be solved by:
1. Create a dedicated PodSecurityPolicy for the service
2. Add to kube-state-metrics clusterrole the permissions to use the PSP - 
```
- apiGroups:
  - extensions
  resourceNames:
  - kube-state-metrics
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.1
- Kube-state-metrics image version: v1.4.0
