### ISSUE TITLE
Add metrics about Vertical Pod Autoscaler recommendations

### ISSUE THREAD

**Issue by jessie-JNing** [kubernetes/kube-state-metrics#781]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

> /kind feature

**What happened**:
[Vertical Pod Autoscaler](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) is release in Kubernetes, which aims to provides recommendations to set appropriate resource request values for Kubernetes pods. 

A number of recommended CPU/memory values are given by VPA, e.g.
```yaml
containerRecommendations:
  - containerName: web
    lowerBound:
      cpu: 10m
      memory: "272054411"
    target:
      cpu: 11m
      memory: "87381333"
    uncappedTarget:
      cpu: 11m
      memory: "442809964"
    upperBound:
      cpu: 11m
      memory: "482354586"
```

**What you expected to happen**:
We would like to have the values(`lowerBound`, `target` and etc.) be collected by kube-state-metrics. 

So that we can compare the actual CPU/memory cost with the recommended values via DataDog or other monitoring tools.
