### ISSUE TITLE
Feature request: export VolumeAttachment metrics

### ISSUE THREAD

**Issue by JensErat** [kubernetes/kube-state-metrics#872]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Kubernetes has a new resource type: [`VolumeAttachment`s](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#volumeattachment-v1-storage-k8s-io). They provide helpful information on where a volume is attached and to alert on unexpected attachment status (for example, differences between information scraped from `node-exporter` and `kube-state-metrics`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by LiliC** [comment]
@JensErat  Thanks for the feature request. Few questions:
- What kind of metrics were you thinking? Can you give some examples of what would be useful for you. Just to avoid any potential high cardinality metrics in advance.
- Would you be interested in implementing this?

**Comment by sbueringer** [comment]
So a typical VolumeAttachment looks like this:

````
apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    name: csi-ff8412cfc3fac5e0e231781de64041282c43510ef839d4db623f57ac10c92c63
  spec:
    attacher: cinder.csi.openstack.org
    nodeName: c12p009-kube-node04
    source:
      persistentVolumeName: pvc-3a84e3d8-b9cf-11e9-a621-fa163ec807ea
  status:
    attached: true
    attachmentMetadata:
      DevicePath: /dev/sdh
````

I think I would like to see at least: nodeName & persistentVolumeName and attached would be also useful

Not sure about attacher & attachmentMetadata. Maybe not for now and if somebody needs them they can always be added later.
